// Code generated by cmd/gen-terminal-palette. DO NOT EDIT.
//
// Source of truth: the "color" token group of the fairtrade design system's
// tokens.json (@peasant-labs/fairtrade), pinned via web/package.json and
// snapshotted at internal/tui/theme/testdata/tokens.json. Regenerate with
// `go run ./cmd/gen-terminal-palette` after bumping the fairtrade pin; a
// freshness test fails if this file drifts from either the committed
// snapshot or (when web/node_modules is installed) the currently-installed
// tokens.json.

package theme

import "charm.land/lipgloss/v2"

// Palette is the closed set of terminal colors sourced from the fairtrade
// design system's "color" token group. One field per token; both Dark and
// Light values are always populated (gen.ParseColorTokens fails closed on any
// token missing either side).
type Palette struct {
	// AddRail is the fairtrade "add-rail" token.
	AddRail ColorPair
	// AddText is the fairtrade "add-text" token.
	AddText ColorPair
	// Amber is the fairtrade "amber" token.
	Amber ColorPair
	// AmberBright is the fairtrade "amber-bright" token.
	AmberBright ColorPair
	// AmberDim is the fairtrade "amber-dim" token.
	AmberDim ColorPair
	// AmberFill is the fairtrade "amber-fill" token.
	AmberFill ColorPair
	// AmberFillInk is the fairtrade "amber-fill-ink" token.
	AmberFillInk ColorPair
	// Canvas is the fairtrade "canvas" token.
	Canvas ColorPair
	// Clay is the fairtrade "clay" token.
	Clay ColorPair
	// Danger is the fairtrade "danger" token.
	Danger ColorPair
	// DangerFg is the fairtrade "danger-fg" token.
	DangerFg ColorPair
	// DelRail is the fairtrade "del-rail" token.
	DelRail ColorPair
	// DelText is the fairtrade "del-text" token.
	DelText ColorPair
	// FocusRing is the fairtrade "focus-ring" token.
	FocusRing ColorPair
	// Ink is the fairtrade "ink" token.
	Ink ColorPair
	// Ink2 is the fairtrade "ink-2" token.
	Ink2 ColorPair
	// Ink3 is the fairtrade "ink-3" token.
	Ink3 ColorPair
	// Ink4 is the fairtrade "ink-4" token.
	Ink4 ColorPair
	// Ink5 is the fairtrade "ink-5" token.
	Ink5 ColorPair
	// InkStrong is the fairtrade "ink-strong" token.
	InkStrong ColorPair
	// Mauve is the fairtrade "mauve" token.
	Mauve ColorPair
	// Olive is the fairtrade "olive" token.
	Olive ColorPair
	// OnAmber is the fairtrade "on-amber" token.
	OnAmber ColorPair
	// Rule is the fairtrade "rule" token.
	Rule ColorPair
	// RuleStrong is the fairtrade "rule-strong" token.
	RuleStrong ColorPair
	// Success is the fairtrade "success" token.
	Success ColorPair
	// SuccessFg is the fairtrade "success-fg" token.
	SuccessFg ColorPair
	// Surface is the fairtrade "surface" token.
	Surface ColorPair
	// Surface2 is the fairtrade "surface-2" token.
	Surface2 ColorPair
	// SurfaceElev is the fairtrade "surface-elev" token.
	SurfaceElev ColorPair
	// SurfaceHover is the fairtrade "surface-hover" token.
	SurfaceHover ColorPair
	// Teal is the fairtrade "teal" token.
	Teal ColorPair
	// Warning is the fairtrade "warning" token.
	Warning ColorPair
	// WarningFg is the fairtrade "warning-fg" token.
	WarningFg ColorPair
}

// GeneratedPalette is the terminal palette generated from the pinned
// fairtrade tokens.json (internal/tui/theme/testdata/tokens.json snapshot).
var GeneratedPalette = Palette{
	AddRail:      ColorPair{Dark: lipgloss.Color("#9aa779"), Light: lipgloss.Color("#586a3c")},
	AddText:      ColorPair{Dark: lipgloss.Color("#bccb96"), Light: lipgloss.Color("#465528")},
	Amber:        ColorPair{Dark: lipgloss.Color("#cba35c"), Light: lipgloss.Color("#8a5f1f")},
	AmberBright:  ColorPair{Dark: lipgloss.Color("#e6c483"), Light: lipgloss.Color("#6e4c16")},
	AmberDim:     ColorPair{Dark: lipgloss.Color("#937a45"), Light: lipgloss.Color("#b09a63")},
	AmberFill:    ColorPair{Dark: lipgloss.Color("#cba35c"), Light: lipgloss.Color("#b8841a")},
	AmberFillInk: ColorPair{Dark: lipgloss.Color("#141003"), Light: lipgloss.Color("#1a1206")},
	Canvas:       ColorPair{Dark: lipgloss.Color("#070706"), Light: lipgloss.Color("#fbfaf7")},
	Clay:         ColorPair{Dark: lipgloss.Color("#c07f64"), Light: lipgloss.Color("#974b32")},
	Danger:       ColorPair{Dark: lipgloss.Color("#c07f64"), Light: lipgloss.Color("#974b32")},
	DangerFg:     ColorPair{Dark: lipgloss.Color("#141003"), Light: lipgloss.Color("#fffdf8")},
	DelRail:      ColorPair{Dark: lipgloss.Color("#c07f64"), Light: lipgloss.Color("#974b32")},
	DelText:      ColorPair{Dark: lipgloss.Color("#daa791"), Light: lipgloss.Color("#82402a")},
	FocusRing:    ColorPair{Dark: lipgloss.Color("#cba35c"), Light: lipgloss.Color("#0d0c09")},
	Ink:          ColorPair{Dark: lipgloss.Color("#e9e5db"), Light: lipgloss.Color("#27241f")},
	Ink2:         ColorPair{Dark: lipgloss.Color("#b8b3a4"), Light: lipgloss.Color("#4a463e")},
	Ink3:         ColorPair{Dark: lipgloss.Color("#9a9488"), Light: lipgloss.Color("#5c574d")},
	Ink4:         ColorPair{Dark: lipgloss.Color("#8a8478"), Light: lipgloss.Color("#6f695e")},
	Ink5:         ColorPair{Dark: lipgloss.Color("#534e45"), Light: lipgloss.Color("#837d72")},
	InkStrong:    ColorPair{Dark: lipgloss.Color("#f8f5ed"), Light: lipgloss.Color("#0d0c09")},
	Mauve:        ColorPair{Dark: lipgloss.Color("#9a8cae"), Light: lipgloss.Color("#594e72")},
	Olive:        ColorPair{Dark: lipgloss.Color("#9aa779"), Light: lipgloss.Color("#586a3c")},
	OnAmber:      ColorPair{Dark: lipgloss.Color("#141003"), Light: lipgloss.Color("#fffdf8")},
	Rule:         ColorPair{Dark: lipgloss.Color("#3c382f"), Light: lipgloss.Color("#c4bca8")},
	RuleStrong:   ColorPair{Dark: lipgloss.Color("#6f6a5f"), Light: lipgloss.Color("#8b836d")},
	Success:      ColorPair{Dark: lipgloss.Color("#9aa779"), Light: lipgloss.Color("#586a3c")},
	SuccessFg:    ColorPair{Dark: lipgloss.Color("#141003"), Light: lipgloss.Color("#fffdf8")},
	Surface:      ColorPair{Dark: lipgloss.Color("#0e0e0c"), Light: lipgloss.Color("#fdfcfa")},
	Surface2:     ColorPair{Dark: lipgloss.Color("#141413"), Light: lipgloss.Color("#f4f2ec")},
	SurfaceElev:  ColorPair{Dark: lipgloss.Color("#1c1b18"), Light: lipgloss.Color("#efece4")},
	SurfaceHover: ColorPair{Dark: lipgloss.Color("#1b1a17"), Light: lipgloss.Color("#edeae2")},
	Teal:         ColorPair{Dark: lipgloss.Color("#7ea69d"), Light: lipgloss.Color("#3a675e")},
	Warning:      ColorPair{Dark: lipgloss.Color("#cba35c"), Light: lipgloss.Color("#8a5f1f")},
	WarningFg:    ColorPair{Dark: lipgloss.Color("#141003"), Light: lipgloss.Color("#fffdf8")},
}
