// Code generated by cmd/gen-redaction-policy. DO NOT EDIT.
//
// The redaction policy, as the share wizard needs it. Generated from
// internal/config so the wizard cannot present a level the product refuses, and
// cannot go on hiding one it has started to offer.
//
// These values were hand-written here once, under a comment saying they mirrored
// the Go side. Widening the offered set then turned three Go packages red and
// left every web test green - including one that asserted the newly-offered level
// must stay hidden. Regenerate with `go run ./cmd/gen-redaction-policy`; a
// freshness test fails if this file and internal/config disagree.

/**
 * Every redaction level the engine defines.
 *
 * This is the RULE-ACTIVATION axis, not a menu: each rule declares the level at
 * which it starts firing.
 * What a user may CHOOSE is the narrower set below.
 */
export const ALL_REDACTION_LEVELS = ['minimal', 'standard', 'maximum'] as const;

/** A level the engine can apply. */
export type RedactionLevel = (typeof ALL_REDACTION_LEVELS)[number];

/**
 * The levels this version offers a user, from config.OfferedRedactionLevels.
 *
 * Asking for any other level produces an opaque 400 mid-wizard, so the step
 * refuses locally with the matching explanation instead.
 */
export const SELECTABLE_REDACTION_LEVELS = ['standard'] as const;

/** A level a user may choose. */
export type SelectableRedactionLevel = (typeof SELECTABLE_REDACTION_LEVELS)[number];

/** The level the wizard starts on, from config.RecommendedRedactionLevel. */
export const DEFAULT_REDACTION_LEVEL: SelectableRedactionLevel = 'standard';

/**
 * Why each unselectable level cannot be chosen, from
 * config.RedactionRefusalReason - the same sentence the CLI and the local API
 * give for the same level, rather than a third phrasing of it.
 */
export const UNSELECTABLE_REDACTION_LEVEL_REASONS: Readonly<Record<string, string>> = {
  'minimal': 'minimal redacts less than standard, and standard is now the single level this version offers, so a scan at that level would not describe any run this version can perform',
  'maximum': 'maximum redaction anonymises code identifiers in transcript content, and this version applies the same redaction on every build of Peasant rather than one that depends on how the binary was compiled, so a scan at that level would not describe any run this version can perform',
};

/**
 * What redaction actually does, in one sentence, from
 * config.RedactionScopeSentence.
 *
 * It is deliberately hedged: pattern matching finds KNOWN patterns and cannot
 * promise it found every one. A completeness claim here would be a defect, so
 * the sentence is generated rather than re-typed - the wizard's hand-written
 * copy had already drifted from the Go one ("shared" against "published" as
 * recorded) while config claimed the hedge lived in exactly one place.
 */
export const REDACTION_SCOPE_SENTENCE = 'It redacts known patterns of secrets, personal data and identifying paths in both metadata and transcript content, which is best effort and not a guarantee that every one was found.';
