// Package redactmock generates the web session-detail redaction mock
// (web/src/lib/session-detail/mock-redactions.ts) FROM the schema contract's
// redaction fixture (schema.RedactionsYAML). The fixture is the single source of
// truth for redaction example DATA; this package owns only the UI presentation
// concern the contract leaf deliberately does NOT carry:
//
//   - contextBefore/contextAfter code snippets, kept in a side-table keyed by
//     case Name and merged at codegen.
//
// Category labels use the public redaction module's canonical CategoryString representation.
//
// A peasant freshness test asserts the committed mock-redactions.ts is
// byte-identical to GenerateMockRedactionsTS(), so the TS mock cannot drift from
// the contract fixture. Regenerate with `go run ./cmd/gen-mock-redactions`.
package redactmock

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/peasant-labs/redact"
	"github.com/peasant-labs/schema"
)

// presentationContext is the UI-only snippet pair shown around a redacted span.
type presentationContext struct {
	before []string
	after  []string
}

// presentationByName is the presentation side-table: UI context snippets keyed by
// fixture case Name. Presentation deliberately lives here (peasant/web), NOT in the
// contract leaf. Every fixture case MUST have an entry — GenerateMockRedactionsTS
// errors on a missing one (no silent empty context), so adding a case forces its
// presentation to be authored here.
var presentationByName = map[string]presentationContext{
	"aws_access_key": {
		before: []string{"  const config = {", "    region: 'us-east-1',"},
		after:  []string{"  }", "  const client = new S3Client(config);"},
	},
	"email_address": {
		before: []string{"  // Contact the team lead", "  const email ="},
		after:  []string{"  sendNotification(email)", `  console.log("Notification sent");`},
	},
	"home_directory": {
		before: []string{"# Project setup", `$ cd \`},
		after:  []string{"$ npm install", "$ npm run dev"},
	},
	"github_token": {
		before: []string{"  headers: {", "    Authorization: `Bearer ${"},
		after:  []string{"    }`,", "    'Content-Type': 'application/json',"},
	},
	"git_remote_url": {
		before: []string{"  // Clone the project repository", "  const remote ="},
		after:  []string{"  await exec(`git clone ${remote}`);", "  process.chdir(repoDir);"},
	},
	"phone_number": {
		before: []string{"  const emergencyContact = {", `    name: "Support Team",`},
		after:  []string{`    extension: "4201",`, "  };"},
	},
	"database_connection": {
		before: []string{"# .env.production", `DATABASE_URL=\`},
		after:  []string{"REDIS_URL=redis://cache.prod.internal:6379", "LOG_LEVEL=info"},
	},
	"workspace_path": {
		before: []string{"  # Deploy to staging", `  ssh deploy@staging "cd \`},
		after:  []string{`    && git pull origin main \`, `    && systemctl restart billing"`},
	},
	"ip_address": {
		before: []string{"  // Local development override", "  const devServer ="},
		after:  []string{"  const port = 3000;", "  app.listen(port, devServer);"},
	},
	"slack_webhook": {
		before: []string{"  // Notify #deployments channel", "  const webhookUrl ="},
		after:  []string{"  await postSlackMessage(webhookUrl, {", "    text: `Deploy ${version} complete`,"},
	},
	"stripe_secret": {
		before: []string{"  const stripe = new Stripe("},
		after:  []string{"    { apiVersion: '2024-12-18.acacia' }", "  );"},
	},
}

// MockRedactionsRelPath is the committed location of the generated TS mock,
// relative to the peasant module root.
var MockRedactionsRelPath = "web/src/lib/session-detail/mock-redactions.ts"

const tsHeader = `// Code generated by ` + "`go run ./cmd/gen-mock-redactions`" + `. DO NOT EDIT.
//
// Source of truth: the schema contract redaction fixture (schema.RedactionsYAML,
// schema repo testdata/session-detail/redactions.yaml). This file is regenerated
// from that fixture; the UI context snippets live in internal/redactmock. To
// change a redaction example, edit the schema
// fixture (RedactionExamples + ` + "`go run ./cmd/schema-gen`" + ` in the schema repo);
// to change UI context, edit internal/redactmock; to change canonical category
// rendering, edit github.com/peasant-labs/redact; then run
// ` + "`go run ./cmd/gen-mock-redactions`" + `. A peasant freshness test fails if this
// committed file drifts from the generator output.

import type { RedactionLevel } from '@/lib/share/redactions';
import type { Redaction, RedactionCategory } from '@/types/messages';

// ---------------------------------------------------------------------------
// Deterministic hash (same as mock-transcript.ts)
// ---------------------------------------------------------------------------

function hashId(sessionId: string): number {
  let hash = 0;
  for (let i = 0; i < sessionId.length; i++) {
    hash = ((hash << 5) - hash + sessionId.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

// ---------------------------------------------------------------------------
// Redaction pool — realistic auto-detected sensitive content.
// originalText + redactedReplacement are the engine-verbatim fixture values; a
// Peasant's conformance test binds them to real public-module output.
// ---------------------------------------------------------------------------

interface RedactionTemplate {
  category: RedactionCategory;
  minimumLevel: RedactionLevel;
  confidence: number;
  description: string;
  originalText: string;
  redactedReplacement: string;
  lineNumber: number;
  contextBefore: string[];
  contextAfter: string[];
}

export type MockRedaction = Redaction & { minimumLevel: RedactionLevel };

`

const tsFooter = `
// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function getMockRedactions(sessionId: string): MockRedaction[] {
  const hash = hashId(sessionId);
  // Pick 5-9 redactions deterministically
  const count = 5 + (hash % 5);
  const startIdx = hash % REDACTION_POOL.length;

  const redactions: MockRedaction[] = [];
  for (let i = 0; i < count; i++) {
    const template = REDACTION_POOL[(startIdx + i) % REDACTION_POOL.length];
    redactions.push({
      id: ` + "`redact-${sessionId.slice(0, 6)}-${i}`" + `,
      ...template,
      status: 'pending',
    });
  }

  return redactions;
}
`

// GenerateMockRedactionsTS builds the byte content of mock-redactions.ts from the
// schema contract fixture (schema.RedactionsYAML, via LoadRedactionExamples),
// rendering each case's category through the public redaction module and merging the UI context
// side-table. It is the ONE function both the cmd writer and the
// freshness test call. Errors if any case has an unmapped category or no
// presentation entry — never emits a silently-defaulted mock.
func GenerateMockRedactionsTS() ([]byte, error) {
	cases, err := schema.LoadRedactionExamples()
	if err != nil {
		return nil, fmt.Errorf("redactmock: load schema redaction fixture: %w", err)
	}
	if len(cases) == 0 {
		return nil, fmt.Errorf("redactmock: schema redaction fixture is empty")
	}

	var buf bytes.Buffer
	buf.WriteString(tsHeader)
	buf.WriteString("const REDACTION_POOL: RedactionTemplate[] = [\n")
	for _, c := range cases {
		if !c.Level.IsValid() {
			return nil, fmt.Errorf(
				"redactmock: fixture case %q has invalid minimum level %q in schema RedactionsYAML; "+
					"the generated web mock cannot apply redaction-level ordering; set level to minimal, standard, or maximum and regenerate",
				c.Name, c.Level,
			)
		}
		category := redact.Category(c.Category)
		if err := category.Validate(); err != nil {
			return nil, err
		}
		renderedCategory := category.String()
		ctx, ok := presentationByName[c.Name]
		if !ok {
			return nil, fmt.Errorf(
				"redactmock: fixture case %q has no presentation entry in presentationByName "+
					"(contextBefore/contextAfter). Add it so the web mock has UI context for this case.",
				c.Name)
		}

		buf.WriteString("  {\n")
		fmt.Fprintf(&buf, "    category: %s,\n", tsSingleQuoted(renderedCategory.String()))
		fmt.Fprintf(&buf, "    minimumLevel: %s,\n", tsSingleQuoted(c.Level.String()))
		fmt.Fprintf(&buf, "    confidence: %d,\n", c.Confidence)
		fmt.Fprintf(&buf, "    description: %s,\n", tsString(currentRuleDescription(c.Description)))
		fmt.Fprintf(&buf, "    originalText: %s,\n", tsString(c.OriginalText))
		fmt.Fprintf(&buf, "    redactedReplacement: %s,\n", tsString(c.RedactedReplacement))
		fmt.Fprintf(&buf, "    lineNumber: %d,\n", c.LineNumber)
		fmt.Fprintf(&buf, "    contextBefore: %s,\n", tsStringArray(ctx.before))
		fmt.Fprintf(&buf, "    contextAfter: %s,\n", tsStringArray(ctx.after))
		buf.WriteString("  },\n")
	}
	buf.WriteString("];\n")
	buf.WriteString(tsFooter)
	return buf.Bytes(), nil
}

// currentRuleDescription corrects the retired Peasant-local attribution still
// present in the pinned schema fixture without changing the fixture's rule text.
func currentRuleDescription(description string) string {
	return strings.Replace(description, "pkg/redact rule:", "github.com/peasant-labs/redact rule:", 1)
}

// tsString renders a Go string as a double-quoted TS string literal with correct
// escaping. It uses encoding/json with HTML escaping DISABLED so angle-bracket
// redaction labels (<AWS_ACCESS_KEY>) stay literal rather than <-escaped.
func tsString(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	// Encoder appends a trailing newline; trim it.
	_ = enc.Encode(s)
	return string(bytes.TrimRight(b.Bytes(), "\n"))
}

// tsSingleQuoted renders a known-safe canonical category value as a
// single-quoted TS literal, matching the RedactionCategory union style. The input
// is always one of CREDENTIAL/PII/PATH/INTERNAL (no escaping needed).
func tsSingleQuoted(s string) string {
	return "'" + s + "'"
}

// tsStringArray renders a slice of strings as an inline TS array literal.
func tsStringArray(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b bytes.Buffer
	b.WriteByte('[')
	for i, it := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(it))
	}
	b.WriteByte(']')
	return b.String()
}
