// Code generated by `go run ./cmd/gen-mock-redactions`. DO NOT EDIT.
//
// Source of truth: the schema contract redaction fixture (schema.RedactionsYAML,
// schema repo testdata/session-detail/redactions.yaml). This file is regenerated
// from that fixture; the UI context snippets live in internal/redactmock. To
// change a redaction example, edit the schema
// fixture (RedactionExamples + `go run ./cmd/schema-gen` in the schema repo);
// to change UI context, edit internal/redactmock; to change canonical category
// rendering, edit github.com/peasant-labs/redact; then run
// `go run ./cmd/gen-mock-redactions`. A peasant freshness test fails if this
// committed file drifts from the generator output.

import type { RedactionLevel } from '@/lib/share/redactions';
import type { Redaction, RedactionCategory } from '@/types/messages';

// ---------------------------------------------------------------------------
// Deterministic hash (same as mock-transcript.ts)
// ---------------------------------------------------------------------------

function hashId(sessionId: string): number {
  let hash = 0;
  for (let i = 0; i < sessionId.length; i++) {
    hash = ((hash << 5) - hash + sessionId.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

// ---------------------------------------------------------------------------
// Redaction pool — realistic auto-detected sensitive content.
// originalText + redactedReplacement are the engine-verbatim fixture values; a
// Peasant's conformance test binds them to real public-module output.
// ---------------------------------------------------------------------------

interface RedactionTemplate {
  category: RedactionCategory;
  minimumLevel: RedactionLevel;
  confidence: number;
  description: string;
  originalText: string;
  redactedReplacement: string;
  lineNumber: number;
  contextBefore: string[];
  contextAfter: string[];
}

export type MockRedaction = Redaction & { minimumLevel: RedactionLevel };

const REDACTION_POOL: RedactionTemplate[] = [
  {
    category: 'CREDENTIAL',
    minimumLevel: 'minimal',
    confidence: 98,
    description: "AWS access key ID (github.com/peasant-labs/redact rule: aws_access_key)",
    originalText: "AKIAIOSFODNN7EXAMPLE",
    redactedReplacement: "<AWS_ACCESS_KEY>",
    lineNumber: 142,
    contextBefore: ["  const config = {", "    region: 'us-east-1',"],
    contextAfter: ["  }", "  const client = new S3Client(config);"],
  },
  {
    category: 'PII',
    minimumLevel: 'standard',
    confidence: 94,
    description: "Email address (github.com/peasant-labs/redact rule: email)",
    originalText: "vitor.eduardo@company.com",
    redactedReplacement: "<EMAIL>",
    lineNumber: 587,
    contextBefore: ["  // Contact the team lead", "  const email ="],
    contextAfter: ["  sendNotification(email)", "  console.log(\"Notification sent\");"],
  },
  {
    category: 'PATH',
    minimumLevel: 'minimal',
    confidence: 72,
    description: "Unix home directory path with username (github.com/peasant-labs/redact rule: unix_home_path)",
    originalText: "/Users/acme-dev/Projects/internal-api",
    redactedReplacement: "/Users/<USER>/Projects/internal-api",
    lineNumber: 23,
    contextBefore: ["# Project setup", "$ cd \\"],
    contextAfter: ["$ npm install", "$ npm run dev"],
  },
  {
    category: 'CREDENTIAL',
    minimumLevel: 'minimal',
    confidence: 96,
    description: "GitHub personal access token (github.com/peasant-labs/redact rule: github_pat)",
    originalText: "ghp_xK9mN2pL4qR7sT8vW1yZ3aB5cD6eF0gH12ab",
    redactedReplacement: "<GITHUB_PAT>",
    lineNumber: 310,
    contextBefore: ["  headers: {", "    Authorization: `Bearer ${"],
    contextAfter: ["    }`,", "    'Content-Type': 'application/json',"],
  },
  {
    category: 'INTERNAL',
    minimumLevel: 'maximum',
    confidence: 61,
    description: "Git remote URL exposing project identity (github.com/peasant-labs/redact rule: git_remote_https)",
    originalText: "https://github.com/acme-corp/internal-api",
    redactedReplacement: "<PROJECT_URL>",
    lineNumber: 445,
    contextBefore: ["  // Clone the project repository", "  const remote ="],
    contextAfter: ["  await exec(`git clone ${remote}`);", "  process.chdir(repoDir);"],
  },
  {
    category: 'PII',
    minimumLevel: 'standard',
    confidence: 89,
    description: "US phone number (github.com/peasant-labs/redact rule: phone_us)",
    originalText: "+1-555-867-5309",
    redactedReplacement: "<PHONE>",
    lineNumber: 712,
    contextBefore: ["  const emergencyContact = {", "    name: \"Support Team\","],
    contextAfter: ["    extension: \"4201\",", "  };"],
  },
  {
    category: 'CREDENTIAL',
    minimumLevel: 'minimal',
    confidence: 99,
    description: "URL with embedded basic-auth credentials (github.com/peasant-labs/redact rule: basic_auth_uri)",
    originalText: "postgresql://admin:s3cretPass99@db.prod.internal:5432/maindb",
    redactedReplacement: "postgresql://<BASIC_AUTH_URI>@db.prod.internal:5432/maindb",
    lineNumber: 18,
    contextBefore: ["# .env.production", "DATABASE_URL=\\"],
    contextAfter: ["REDIS_URL=redis://cache.prod.internal:6379", "LOG_LEVEL=info"],
  },
  {
    category: 'PATH',
    minimumLevel: 'minimal',
    confidence: 65,
    description: "Unix home directory path with username (github.com/peasant-labs/redact rule: unix_home_path)",
    originalText: "/home/deploy/apps/acme-billing-service",
    redactedReplacement: "/home/<USER>/apps/acme-billing-service",
    lineNumber: 891,
    contextBefore: ["  # Deploy to staging", "  ssh deploy@staging \"cd \\"],
    contextAfter: ["    && git pull origin main \\", "    && systemctl restart billing\""],
  },
  {
    category: 'PII',
    minimumLevel: 'standard',
    confidence: 85,
    description: "IPv4 address (github.com/peasant-labs/redact rule: ip_address)",
    originalText: "192.168.1.42",
    redactedReplacement: "<IP_ADDRESS>",
    lineNumber: 156,
    contextBefore: ["  // Local development override", "  const devServer ="],
    contextAfter: ["  const port = 3000;", "  app.listen(port, devServer);"],
  },
  {
    category: 'CREDENTIAL',
    minimumLevel: 'minimal',
    confidence: 58,
    description: "Slack incoming webhook URL (github.com/peasant-labs/redact rule: slack_webhook_url)",
    originalText: "https://hooks.slack.com/services/T024BE7LD/B0DAF2RC3/bJTqg8NS27FYm2pQL0jAiE",
    redactedReplacement: "<SLACK_WEBHOOK_URL>",
    lineNumber: 234,
    contextBefore: ["  // Notify #deployments channel", "  const webhookUrl ="],
    contextAfter: ["  await postSlackMessage(webhookUrl, {", "    text: `Deploy ${version} complete`,"],
  },
  {
    category: 'CREDENTIAL',
    minimumLevel: 'minimal',
    confidence: 92,
    description: "Stripe API secret key (github.com/peasant-labs/redact rule: stripe_key)",
    originalText: "sk_live_4eC39HqLyjWDarjtT1zdp7dc",
    redactedReplacement: "<STRIPE_KEY>",
    lineNumber: 67,
    contextBefore: ["  const stripe = new Stripe("],
    contextAfter: ["    { apiVersion: '2024-12-18.acacia' }", "  );"],
  },
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function getMockRedactions(sessionId: string): MockRedaction[] {
  const hash = hashId(sessionId);
  // Pick 5-9 redactions deterministically
  const count = 5 + (hash % 5);
  const startIdx = hash % REDACTION_POOL.length;

  const redactions: MockRedaction[] = [];
  for (let i = 0; i < count; i++) {
    const template = REDACTION_POOL[(startIdx + i) % REDACTION_POOL.length];
    redactions.push({
      id: `redact-${sessionId.slice(0, 6)}-${i}`,
      ...template,
      status: 'pending',
    });
  }

  return redactions;
}
