-- Generated by scripts/store-baseline-gen; do not edit by hand.
-- Regenerate with: go generate ./internal/store
--
-- A consolidated head-schema snapshot for brand-new databases. Existing
-- databases keep the shipped migration chain as their only upgrade path.

CREATE TABLE annotation_classes (
    id           TEXT PRIMARY KEY,
    class        TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description  TEXT
) STRICT;

CREATE TABLE annotation_families (
    id           TEXT PRIMARY KEY,
    family       TEXT NOT NULL UNIQUE,
    class_id     TEXT NOT NULL REFERENCES annotation_classes(id),
    display_name TEXT NOT NULL,
    description  TEXT
) STRICT;

CREATE TABLE annotation_run_state (
    session_id TEXT PRIMARY KEY,
    session_entries_hash TEXT NOT NULL CHECK (
        length(session_entries_hash) = 64 AND session_entries_hash NOT GLOB '*[^0-9a-f]*'
    ),
    compute_version INTEGER NOT NULL,
    classifier_version INTEGER NOT NULL,
    annotated_at INTEGER NOT NULL, metrics_output_hash TEXT CHECK (
    metrics_output_hash IS NULL OR (length(metrics_output_hash) = 64 AND metrics_output_hash NOT GLOB '*[^0-9a-f]*')
),
    FOREIGN KEY(session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE annotation_statuses (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE annotation_target_anchors (
    annotation_id TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    entry_index INTEGER,
    end_index INTEGER,
    state TEXT NOT NULL CHECK (state IN ('resolved', 'unresolved', 'superseded')),
    entry_id TEXT,
    tool_call_id TEXT,
    entry_type TEXT,
    role TEXT,
    part_type TEXT,
    content_fingerprint TEXT,
    updated_at INTEGER NOT NULL,
    CHECK ((state = 'resolved' AND entry_index IS NOT NULL AND end_index IS NOT NULL AND end_index > entry_index) OR state IN ('unresolved', 'superseded'))
) STRICT;

CREATE TABLE annotation_target_annotations (
    annotation_id        TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    target_annotation_id TEXT NOT NULL REFERENCES annotations(id)
) STRICT;

CREATE TABLE annotation_target_associations (
    annotation_id  TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    association_id TEXT NOT NULL REFERENCES session_commit_associations(association_id)
) STRICT;

CREATE TABLE "annotation_target_entries" (
    annotation_id TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    session_id    TEXT NOT NULL,
    entry_index   INTEGER NOT NULL,
    end_index     INTEGER NOT NULL,
    CHECK (end_index > entry_index)
) STRICT;

CREATE TABLE annotation_target_projects (
    annotation_id TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    project_hash  TEXT NOT NULL REFERENCES projects(project_hash)
) STRICT;

CREATE TABLE annotation_target_sessions (
    annotation_id TEXT PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    session_id    TEXT NOT NULL REFERENCES sessions(session_id)
) STRICT;

CREATE TABLE annotation_type_deps (
    annotation_type_id TEXT NOT NULL REFERENCES annotation_types(id),
    depends_on_id      TEXT NOT NULL REFERENCES annotation_types(id),
    required           INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
    rationale          TEXT,
    PRIMARY KEY (annotation_type_id, depends_on_id),
    CHECK (annotation_type_id != depends_on_id)
) STRICT;

CREATE TABLE annotation_type_target_kinds (
    annotation_type_id TEXT NOT NULL REFERENCES annotation_types(id) ON DELETE CASCADE,
    target_kind_id     INTEGER NOT NULL REFERENCES target_kinds(id),
    PRIMARY KEY (annotation_type_id, target_kind_id)
) STRICT;

CREATE TABLE annotation_types (
    id                 TEXT PRIMARY KEY,
    type_id            TEXT NOT NULL UNIQUE,
    version            INTEGER NOT NULL DEFAULT 1,
    display_name       TEXT NOT NULL,
    description        TEXT,
    family_id          TEXT NOT NULL REFERENCES annotation_families(id),
    value_domain_kind_id INTEGER NOT NULL REFERENCES value_domain_kinds(id),
    datatype           TEXT NOT NULL
                       CHECK (datatype IN ('text', 'integer', 'real', 'boolean')),
    value_constraint   TEXT NOT NULL,
    lower_is_better    INTEGER CHECK (lower_is_better IN (0, 1)),
    status_id          INTEGER NOT NULL DEFAULT 1 REFERENCES annotation_statuses(id),
    origin_id          INTEGER NOT NULL REFERENCES type_origins(id),
    priority_override  INTEGER,
    created_at         INTEGER NOT NULL,
    updated_at         INTEGER,
    deprecated_at      INTEGER,
    superseded_by      TEXT REFERENCES annotation_types(id), scale_kind_id INTEGER REFERENCES scale_kinds(id),
    CHECK (type_id LIKE '%.%')
) STRICT;

CREATE TABLE annotations (
    id                 TEXT PRIMARY KEY,
    target_kind_id     INTEGER NOT NULL REFERENCES target_kinds(id),
    annotation_type_id TEXT NOT NULL REFERENCES annotation_types(id),
    annotator_id       TEXT NOT NULL REFERENCES annotators(id),
    value              TEXT NOT NULL,
    confidence         REAL,
    reason             TEXT,
    provenance         TEXT,
    is_primary         INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
    content_hash       TEXT,
    created_at         INTEGER NOT NULL,
    updated_at         INTEGER,
    superseded_by      TEXT REFERENCES annotations(id)
, retired_at INTEGER) STRICT;

CREATE TABLE annotator_kinds (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE annotators (
    id            TEXT PRIMARY KEY,
    kind_id       INTEGER NOT NULL REFERENCES annotator_kinds(id),
    name          TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    description   TEXT,
    model_id      TEXT,
    provider_key  TEXT,
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'inactive')),
    created_at    INTEGER NOT NULL,
    FOREIGN KEY (model_id, provider_key) REFERENCES models(model_id, provider_key),
    CHECK (kind_id != 2 OR (model_id IS NOT NULL AND provider_key IS NOT NULL)),
    CHECK (kind_id = 2 OR (model_id IS NULL AND provider_key IS NULL))
) STRICT;

CREATE TABLE claude_transcript_evidence (
  source_path TEXT PRIMARY KEY,
  scope TEXT NOT NULL CHECK(scope IN ('root', 'subagent')),
  mod_time_unix_nano INTEGER NOT NULL,
  size_bytes INTEGER NOT NULL CHECK(size_bytes >= 0),
  has_conversation INTEGER NOT NULL CHECK(has_conversation IN (0, 1)),
  identity_team TEXT,
  identity_name TEXT,
  spawns_json TEXT NOT NULL CHECK(json_valid(spawns_json)),
  title TEXT NOT NULL,
  branch TEXT NOT NULL,
  cwd TEXT NOT NULL, origin TEXT NOT NULL DEFAULT ''
  CHECK (origin IN ('', 'user', 'agent', 'unknown')),
  CHECK((identity_team IS NULL) = (identity_name IS NULL))
) STRICT;

CREATE TABLE daily_summary (
    date_utc        TEXT PRIMARY KEY,
    session_count   INTEGER NOT NULL DEFAULT 0,
    tokens_in       INTEGER NOT NULL DEFAULT 0,
    tokens_out      INTEGER NOT NULL DEFAULT 0,
    tokens_total    INTEGER NOT NULL DEFAULT 0,
    avg_duration_ms REAL    NOT NULL DEFAULT 0,
    avg_turns       REAL    NOT NULL DEFAULT 0,
    tool_call_count INTEGER NOT NULL DEFAULT 0
, total_cost_usd REAL, avg_cost_per_session_usd REAL, acceptance_rate REAL) STRICT;

CREATE TABLE daily_summary_by_project (
    date_utc       TEXT NOT NULL,
    project_hash   TEXT NOT NULL,
    project_path   TEXT,
    session_count  INTEGER NOT NULL DEFAULT 0,
    total_tokens   INTEGER NOT NULL DEFAULT 0,
    total_tool_calls INTEGER NOT NULL DEFAULT 0,
    total_duration_minutes REAL NOT NULL DEFAULT 0,
    resolved_count INTEGER NOT NULL DEFAULT 0,
    failed_count   INTEGER NOT NULL DEFAULT 0,
    partial_count  INTEGER NOT NULL DEFAULT 0,
    avg_spec_quality REAL,
    acceptance_rate REAL,
    total_cost_usd REAL,
    PRIMARY KEY (date_utc, project_hash)
) STRICT;

CREATE TABLE daily_summary_harness (
    date_utc TEXT NOT NULL,
    model_harness TEXT NOT NULL CHECK (model_harness IN ('claude-code','opencode','codex','gemini-cli','cursor','antigravity','strike','pi')),
    session_count INTEGER NOT NULL DEFAULT 0,
    tokens_in INTEGER NOT NULL DEFAULT 0,
    tokens_out INTEGER NOT NULL DEFAULT 0,
    tokens_total INTEGER NOT NULL DEFAULT 0,
    avg_duration_ms REAL NOT NULL DEFAULT 0,
    avg_turns REAL NOT NULL DEFAULT 0,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (date_utc, model_harness)
) STRICT, WITHOUT ROWID;

CREATE TABLE file_familiarity (
    project_hash       TEXT NOT NULL REFERENCES projects(project_hash),
    file_path          TEXT NOT NULL,
    familiarity_depth  INTEGER NOT NULL DEFAULT 0,
    session_count      INTEGER NOT NULL DEFAULT 0,
    total_turns        INTEGER NOT NULL DEFAULT 0,
    total_human_turns  INTEGER NOT NULL DEFAULT 0,
    first_engaged_at   TEXT,
    last_engaged_at    TEXT,
    PRIMARY KEY (project_hash, file_path)
) STRICT;

CREATE TABLE host_slugs (
    opaque_id        TEXT PRIMARY KEY,
    host_slug        TEXT NOT NULL,
    git_remote       TEXT,
    canonical_remote TEXT
) STRICT;

CREATE TABLE index_log (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id        TEXT NOT NULL,
    provider          TEXT NOT NULL,
    outcome           TEXT NOT NULL CHECK (outcome IN ('indexed','reindexed','fallback','skipped','error')),
    index_version     INTEGER NOT NULL,
    entries_count     INTEGER NOT NULL DEFAULT 0,
    source_path       TEXT,
    original_root     TEXT,
    reason            TEXT,
    started_at        INTEGER NOT NULL,
    finished_at       INTEGER,
    error_message     TEXT
, index_format_version INTEGER CHECK (index_format_version > 0)) STRICT;

CREATE TABLE ingest_log (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at        INTEGER NOT NULL,
    finished_at       INTEGER,
    sessions_new      INTEGER NOT NULL DEFAULT 0,
    sessions_updated  INTEGER NOT NULL DEFAULT 0,
    sessions_unchanged INTEGER NOT NULL DEFAULT 0,
    sessions_error    INTEGER NOT NULL DEFAULT 0,
    indexed_count     INTEGER NOT NULL DEFAULT 0,
    computed_count    INTEGER NOT NULL DEFAULT 0,
    error_message     TEXT,
    source_path       TEXT
) STRICT;

CREATE TABLE lesson_sources (
    id                    TEXT PRIMARY KEY,
    lesson_id             TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    episode_annotation_id TEXT NOT NULL,
    session_id            TEXT NOT NULL,
    created_at            INTEGER NOT NULL,
    UNIQUE(lesson_id, episode_annotation_id, session_id)
) STRICT;

CREATE TABLE "lessons" (
    id                     TEXT PRIMARY KEY,
    episode_annotation_id  TEXT NOT NULL,
    session_id             TEXT NOT NULL,
    topic                  TEXT NOT NULL,
    rule                   TEXT NOT NULL,
    failure_mode           TEXT NOT NULL,
    situation_embedding    BLOB,
    created_at             INTEGER NOT NULL
) STRICT;

CREATE TABLE memory_injection_log (
    id           TEXT PRIMARY KEY,
    project_path TEXT NOT NULL,
    event        TEXT NOT NULL CHECK (event IN ('on', 'off')),
    created_at   INTEGER NOT NULL
) STRICT;

CREATE TABLE models (
    model_id                 TEXT NOT NULL,
    provider_key             TEXT NOT NULL,
    display_name             TEXT NOT NULL,
    family                   TEXT,
    context_window           INTEGER,
    max_output               INTEGER,
    reasoning                INTEGER NOT NULL DEFAULT 0,
    tool_call                INTEGER NOT NULL DEFAULT 0,
    cost_input_per_mtok      REAL,
    cost_output_per_mtok     REAL,
    cost_reasoning_per_mtok  REAL,
    cost_cache_read_per_mtok REAL,
    cost_cache_write_per_mtok REAL,
    release_date             TEXT,
    last_synced              TEXT NOT NULL,
    PRIMARY KEY (model_id, provider_key)
) STRICT;

CREATE TABLE opencode_session_seq_cursor (
  session_id TEXT PRIMARY KEY,
  last_seq INTEGER NOT NULL CHECK(last_seq >= 0)
) STRICT;

CREATE TABLE pending_annotations (
    id          TEXT PRIMARY KEY,
    session_id  TEXT NOT NULL,
    type_id     TEXT NOT NULL,
    value       TEXT NOT NULL,
    entry_index INTEGER,
    end_index   INTEGER,
    created_at  INTEGER NOT NULL
) STRICT;

CREATE TABLE projects (
    project_hash     TEXT PRIMARY KEY,
    canonical_cwd    TEXT,
    canonical_remote TEXT
) STRICT;

CREATE TABLE publication_attempt_diagnostics (
  id INTEGER PRIMARY KEY,
  village_origin TEXT NOT NULL,
  owner_user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  project_hash TEXT NOT NULL,
  attempted_at INTEGER NOT NULL CHECK(attempted_at > 0),
  stage TEXT NOT NULL CHECK(stage IN ('publish','validate','visibility','persist')),
  message TEXT NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE pulled_annotations (
    village_host      TEXT NOT NULL,
    content_hash      TEXT NOT NULL,
    transcript_id     TEXT NOT NULL,
    local_session_id  TEXT,
    author_user_id    TEXT NOT NULL,
    author_username   TEXT NOT NULL,
    payload           TEXT NOT NULL,
    pulled_at         INTEGER NOT NULL,
    retracted_at      INTEGER,
    PRIMARY KEY (village_host, content_hash)
) STRICT;

CREATE TABLE pulled_transcripts (
    village_host      TEXT NOT NULL,
    transcript_id     TEXT NOT NULL,
    owner_user_id     TEXT NOT NULL,
    owner_username    TEXT NOT NULL,
    local_session_id  TEXT,
    title             TEXT,
    harness           TEXT,
    project_name      TEXT,
    content_hash      TEXT NOT NULL,
    visibility        TEXT NOT NULL,
    pull_dir          TEXT NOT NULL,
    first_pulled_at   INTEGER NOT NULL,
    last_pulled_at    INTEGER NOT NULL,
    annotation_count  INTEGER NOT NULL DEFAULT 0, license_id TEXT CHECK (license_id IN ('CC0-1.0', 'CC-BY-4.0', 'CC-BY-SA-4.0')),
    PRIMARY KEY (village_host, transcript_id)
) STRICT;

CREATE TABLE push_log (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at         INTEGER NOT NULL,
    finished_at        INTEGER,
    village_url    TEXT NOT NULL,
    sessions_pushed    INTEGER DEFAULT 0,
    sessions_updated   INTEGER DEFAULT 0,
    sessions_skipped   INTEGER DEFAULT 0,
    sessions_failed    INTEGER DEFAULT 0,
    error_message      TEXT,
    user_id            TEXT,
    username           TEXT
) STRICT;

CREATE TABLE scale_kinds (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE session_captured_stats (
  session_id             TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
  turn_count             INTEGER,
  input_submission_count INTEGER CHECK(input_submission_count IS NULL OR (input_submission_count BETWEEN 0 AND 9007199254740991)),
  tool_call_count        INTEGER,
  subagent_count         INTEGER,
  duration_ms            INTEGER,
  tokens_in              INTEGER,
  tokens_out             INTEGER,
  thought_tokens         INTEGER,
  cached_read_tokens     INTEGER,
  cached_write_tokens    INTEGER,
  seed_json              TEXT CHECK(seed_json IS NULL OR json_valid(seed_json)),
  source                 TEXT NOT NULL CHECK(source IN ('harness','derived')),
  updated_at_ms          INTEGER NOT NULL CHECK(updated_at_ms >= 0),
  overflow               TEXT
) STRICT;

CREATE TABLE session_commands (
    session_id   TEXT NOT NULL,
    entry_index  INTEGER NOT NULL,
    command_name TEXT NOT NULL,
    command_args TEXT,
    PRIMARY KEY (session_id, entry_index),
    FOREIGN KEY (session_id, entry_index) REFERENCES session_entries(session_id, entry_index) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_commit_associations (
    association_id       TEXT PRIMARY KEY,
    session_id           TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    observed_commit_hash TEXT NOT NULL,
    subject              TEXT,
    author_time          INTEGER,
    created_at           INTEGER NOT NULL DEFAULT (unixepoch('now') * 1000),
    UNIQUE (session_id, observed_commit_hash)
) STRICT;

CREATE TABLE session_commits (
    session_id   TEXT NOT NULL REFERENCES sessions(session_id),
    commit_hash  TEXT NOT NULL,
    author_name  TEXT,
    author_email TEXT,
    message      TEXT,
    commit_time  INTEGER,
    author_time  INTEGER,
    created_at   INTEGER NOT NULL DEFAULT (unixepoch('now') * 1000),
    PRIMARY KEY (session_id, commit_hash)
) STRICT;

CREATE TABLE session_content (
  session_id  TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  digest      TEXT NOT NULL CHECK(length(digest) = 64),
  byte_length INTEGER NOT NULL CHECK(byte_length >= 0),
  chunk_count INTEGER GENERATED ALWAYS AS ((byte_length + 65535) / 65536) VIRTUAL,
  PRIMARY KEY (session_id, digest)
) STRICT, WITHOUT ROWID;

CREATE TABLE session_content_captures (
 session_id TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
 status TEXT NOT NULL CHECK(status IN ('complete','incomplete','failed')),
 source_authority TEXT NOT NULL CHECK(source_authority IN ('new_ingest','peasant_snapshot','provider_source','none')),
 transcript_origin INTEGER NOT NULL DEFAULT 0,
 capture_format TEXT NOT NULL CHECK(capture_format IN ('full','preview_only','legacy_preview_only')),
 entry_count INTEGER NOT NULL CHECK(entry_count >= 0),
 content_row_count INTEGER NOT NULL CHECK(content_row_count >= 0),
 full_capture_sha256 TEXT CHECK(full_capture_sha256 IS NULL OR length(full_capture_sha256)=64),
 captured_at_ms INTEGER NOT NULL,
 failure_code TEXT,
 failure_message TEXT,
	publication_capture_revision INTEGER NOT NULL DEFAULT 0 CHECK(publication_capture_revision >= 0),
 CHECK(status != 'complete' OR (full_capture_sha256 IS NOT NULL AND failure_code IS NULL AND failure_message IS NULL))
) STRICT;

CREATE TABLE session_content_chunks (
  session_id  TEXT NOT NULL,
  digest      TEXT NOT NULL,
  chunk_index INTEGER NOT NULL CHECK(chunk_index >= 0),
  data        BLOB NOT NULL CHECK(length(data) BETWEEN 1 AND 65536),
  UNIQUE (session_id, digest, chunk_index),
  FOREIGN KEY (session_id, digest) REFERENCES session_content(session_id, digest) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_context_segment_refs (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  segment_ordinal INTEGER NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  source_entry_ref TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, segment_ordinal, ordinal),
  FOREIGN KEY (session_id, generation_id, segment_ordinal)
    REFERENCES session_context_segments(session_id, generation_id, segment_ordinal) ON DELETE CASCADE
) STRICT;

CREATE TABLE "session_context_segments" (
  session_id                TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id             TEXT NOT NULL,
  segment_ordinal           INTEGER NOT NULL CHECK(segment_ordinal >= 0),
  logical_session_id        TEXT,
  physical_source_id        TEXT NOT NULL,
  coordinate_kind           TEXT NOT NULL,
  start_coordinate          INTEGER,
  end_exclusive             INTEGER,
  decoded_byte_start        INTEGER,
  decoded_byte_end_exclusive INTEGER,
  inclusion                 TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, segment_ordinal)
) STRICT;

CREATE TABLE session_entries (
    session_id      TEXT NOT NULL REFERENCES sessions(session_id),
    entry_index     INTEGER NOT NULL,
    provider        TEXT NOT NULL,
    entry_type      TEXT NOT NULL CHECK (entry_type IN ('text','tool_use','tool_result','thinking','system','error','result')),
    role            TEXT NOT NULL CHECK (role IN ('user','assistant','tool','system')),
    timestamp_ms    INTEGER,
    content_preview TEXT,
    tokens_in       INTEGER,
    tokens_out      INTEGER,
    has_tool_use    INTEGER NOT NULL DEFAULT 0 CHECK (has_tool_use IN (0,1)),
    tool_names_csv  TEXT,
    has_thinking    INTEGER NOT NULL DEFAULT 0 CHECK (has_thinking IN (0,1)),
    is_error        INTEGER NOT NULL DEFAULT 0 CHECK (is_error IN (0,1)),
    raw_byte_length INTEGER,
    tool_call_id     TEXT,
    entry_id        TEXT,
    parent_entry_id TEXT,
    extra           TEXT, depth INTEGER NOT NULL DEFAULT 0, parent_index INTEGER, tool_input TEXT, tool_output TEXT, tool_kind TEXT, stop_reason TEXT, part_type TEXT,
    PRIMARY KEY (session_id, entry_index)
) STRICT;

CREATE TABLE session_entries_ext (
    session_id   TEXT NOT NULL,
    entry_index  INTEGER NOT NULL,
    key          TEXT NOT NULL,
    value_text   TEXT,
    value_int    INTEGER,
    value_real   REAL,
    PRIMARY KEY (session_id, entry_index, key),
    FOREIGN KEY (session_id, entry_index)
      REFERENCES session_entries(session_id, entry_index) ON DELETE CASCADE
) STRICT;

CREATE VIRTUAL TABLE session_entries_fts USING fts5(
    content_preview,
    tool_input,
    tool_output,
    session_id UNINDEXED,
    entry_index UNINDEXED,
    content='session_entries',
    content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE TABLE session_entry_bodies (
  body_id          INTEGER PRIMARY KEY CHECK(body_id >= 1125899906842624),
  session_id       TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  body_digest      TEXT NOT NULL CHECK(length(body_digest) = 64),
  entry_index      INTEGER NOT NULL CHECK(entry_index >= 0),
  harness          TEXT NOT NULL,
  entry_type       TEXT NOT NULL,
  role             TEXT NOT NULL,
  timestamp_ms     INTEGER,
  content_preview  TEXT,
  tokens_in        INTEGER,
  tokens_out       INTEGER,
  has_tool_use     INTEGER NOT NULL CHECK(has_tool_use IN (0,1)),
  tool_kind        TEXT,
  tool_names_csv   TEXT,
  has_thinking     INTEGER NOT NULL CHECK(has_thinking IN (0,1)),
  is_error         INTEGER NOT NULL CHECK(is_error IN (0,1)),
  stop_reason      TEXT,
  raw_byte_length  INTEGER,
  tool_call_id     TEXT,
  entry_id         TEXT,
  parent_entry_id  TEXT,
  depth            INTEGER NOT NULL,
  parent_index     INTEGER,
  tool_input       TEXT,
  tool_output      TEXT,
  model_id         TEXT,
  tokens_reasoning INTEGER,
  cache_read       INTEGER,
  cache_write      INTEGER,
  extra            TEXT,
  extra_verbatim   TEXT,
  part_type        TEXT,
  source_entry_ref TEXT,
  prov_origin      TEXT,
  prov_actor       TEXT,
  prov_delivery    TEXT,
  prov_ownership   TEXT,
  prov_evidence    TEXT,
  prov_input_modality TEXT,
  prov_submission_ref TEXT,
  UNIQUE (session_id, body_digest),
  CHECK (extra IS NULL OR extra_verbatim IS NULL)
) STRICT;

CREATE TABLE session_entry_full_content (
 session_id TEXT NOT NULL,
 entry_index INTEGER NOT NULL,
 full_byte_length INTEGER NOT NULL CHECK(full_byte_length >= 0),
 full_sha256 TEXT NOT NULL CHECK(length(full_sha256)=64),
 preview_byte_length INTEGER NOT NULL CHECK(preview_byte_length >= 0),
 preview_sha256 TEXT NOT NULL CHECK(length(preview_sha256)=64),
 preview_is_full INTEGER NOT NULL CHECK(preview_is_full IN (0,1)),
 chunk_count INTEGER NOT NULL CHECK(chunk_count >= 0),
 captured_at_ms INTEGER NOT NULL,
 PRIMARY KEY(session_id,entry_index),
 FOREIGN KEY(session_id,entry_index) REFERENCES session_entries(session_id,entry_index) ON DELETE CASCADE
) STRICT, WITHOUT ROWID;

CREATE TABLE session_entry_full_content_chunks (
 session_id TEXT NOT NULL,
 entry_index INTEGER NOT NULL,
 chunk_index INTEGER NOT NULL,
 byte_offset INTEGER NOT NULL CHECK(byte_offset >= 0),
 byte_length INTEGER NOT NULL CHECK(byte_length >= 0),
 chunk_sha256 TEXT NOT NULL CHECK(length(chunk_sha256)=64),
 data BLOB NOT NULL,
 PRIMARY KEY(session_id,entry_index,chunk_index),
 FOREIGN KEY(session_id,entry_index) REFERENCES session_entry_full_content(session_id,entry_index) ON DELETE CASCADE
) STRICT, WITHOUT ROWID;

CREATE TABLE session_files (
    session_id    TEXT NOT NULL REFERENCES sessions(session_id),
    file_path     TEXT NOT NULL,
    interaction   TEXT NOT NULL DEFAULT 'mentioned' CHECK (interaction IN ('mentioned','read','discussed','questioned')),
    turn_count    INTEGER NOT NULL DEFAULT 0,
    human_turns   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (session_id, file_path)
) STRICT;

CREATE TABLE session_generation_associations (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  association_id TEXT NOT NULL,
  observed_commit_hash TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, ordinal),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_generation_commits (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  hash TEXT NOT NULL,
  message TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL,
  commit_time INTEGER NOT NULL,
  author_time INTEGER NOT NULL,
  PRIMARY KEY (session_id, generation_id, ordinal),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_generation_content (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  source_entry_ref TEXT NOT NULL,
  digest TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, source_entry_ref),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id, digest) REFERENCES session_content(session_id, digest)
) STRICT, WITHOUT ROWID;

CREATE TABLE session_generation_diagnostics (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  error_type TEXT NOT NULL,
  location TEXT NOT NULL,
  message TEXT NOT NULL,
  remediation TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, ordinal),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_generation_entries (
  session_id       TEXT NOT NULL,
  generation_id    TEXT NOT NULL,
  partition_id     INTEGER NOT NULL CHECK(partition_id >= 0),
  entry_index      INTEGER NOT NULL CHECK(entry_index >= 0),
  source_entry_ref TEXT,
  body_digest      TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, partition_id, entry_index),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id, body_digest)   REFERENCES session_entry_bodies(session_id, body_digest)
) STRICT;

CREATE TABLE session_generation_subagents (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  subagent_session_id TEXT NOT NULL,
  parent_uuid TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, ordinal),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_generation_title_refs (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  source_entry_ref TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, ordinal),
  FOREIGN KEY (session_id, generation_id) REFERENCES session_generations(session_id, generation_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_generations (
  session_id             TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id          TEXT NOT NULL,
  schema_version         INTEGER NOT NULL,
  harness                TEXT NOT NULL,
  model                  TEXT NOT NULL,
  version                TEXT NOT NULL,
  ts_start               INTEGER NOT NULL,
  ts_end                 INTEGER NOT NULL,
  ts_ingested            INTEGER,
  source_file_path       TEXT,
  source_format          TEXT NOT NULL,
  git_branch             TEXT,
  git_remote             TEXT,
  git_worktree           TEXT,
  git_tracking           TEXT,
  project_hash           TEXT NOT NULL,
  project_file_path      TEXT,
  project_name           TEXT NOT NULL,
  host_slug              TEXT NOT NULL,
  root_session_id        TEXT,
  purpose                TEXT,
  cwd                    TEXT,
  derived_at             INTEGER,
  content_hash           TEXT NOT NULL,
  metadata_hash          TEXT NOT NULL CHECK(length(metadata_hash) = 64),
  redaction_applied      INTEGER NOT NULL CHECK(redaction_applied IN (0,1)),
  redaction_level        TEXT,
  redaction_rule_set_version TEXT,
  redaction_at_ms        INTEGER,
  redaction_content_hash_at_redact TEXT,
  adapter_version        INTEGER,
  diagnostics_partial    INTEGER CHECK(diagnostics_partial IS NULL OR diagnostics_partial IN (0,1)),
  completeness           TEXT NOT NULL CHECK(completeness IN ('complete','incomplete_new')),
  source_evidence_digest TEXT NOT NULL CHECK(length(source_evidence_digest) = 64),
  index_format_version   INTEGER NOT NULL CHECK(index_format_version = 2),
  candidate_digest       TEXT NOT NULL CHECK(length(candidate_digest) = 64),
  prior_evidence         BLOB,
  installed_at_ms        INTEGER NOT NULL CHECK(installed_at_ms >= 0),
  activated_at_ms        INTEGER CHECK(activated_at_ms IS NULL OR activated_at_ms >= 0),
  PRIMARY KEY (session_id, generation_id)
) STRICT;

CREATE TABLE session_metrics (
    session_id       TEXT PRIMARY KEY REFERENCES sessions(session_id),
    -- Retained v1 columns (no v2 equivalent; independently useful)
    turn_count       INTEGER,
    subagent_count   INTEGER,
    -- v2 QualitySession columns
    title            TEXT,
    outcome          TEXT CHECK(outcome IN ('resolved','partial','failed')),
    total_tokens     INTEGER,
    input_tokens     INTEGER,
    output_tokens    INTEGER,
    tool_calls       INTEGER,
    files_touched    INTEGER,
    lines_changed    INTEGER,
    duration_minutes REAL,
    retry_loops      INTEGER,
    retry_tokens_wasted INTEGER,
    within_session_reverts INTEGER,
    signal_density   REAL,
    spec_quality_score REAL,
    exploration_ratio REAL,
    scope_breadth    INTEGER,
    discovery_turns  INTEGER,
    -- M-series (v2 — stubbed)
    m2_token_outcome_ratio    REAL,
    m3_unique_tool_count      INTEGER,
    m4_error_recovery_count   INTEGER,
    m4_consecutive_error_max  INTEGER,
    m5_context_utilization_pct REAL,
    m5_peak_context_tokens    INTEGER,
    m5_avg_message_tokens     INTEGER,
    m6_output_survival_pct    REAL,
    m6_lines_survived         INTEGER,
    m6_lines_total            INTEGER,
    m7_spec_word_count        INTEGER,
    m7_spec_has_examples      INTEGER NOT NULL DEFAULT 0,
    m7_spec_has_constraints   INTEGER NOT NULL DEFAULT 0,
    -- Metadata
    computed_at      INTEGER,
    compute_version  INTEGER NOT NULL DEFAULT 0
, cost_input_usd REAL, cost_output_usd REAL, cost_reasoning_usd REAL, cost_cache_read_usd REAL, cost_cache_write_usd REAL, cost_total_usd REAL, cost_model_id TEXT, scope TEXT, input_hash TEXT CHECK (
    input_hash IS NULL OR (length(input_hash) = 64 AND input_hash NOT GLOB '*[^0-9a-f]*')
), output_hash TEXT CHECK (
    output_hash IS NULL OR (length(output_hash) = 64 AND output_hash NOT GLOB '*[^0-9a-f]*')
)) STRICT;

CREATE TABLE session_migration_gaps (
  id INTEGER PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id TEXT NOT NULL,
  source_table TEXT NOT NULL,
  source_column TEXT NOT NULL,
  source_ordinal INTEGER NOT NULL CHECK(source_ordinal >= 0),
  observed_json_type TEXT NOT NULL,
  observed_length INTEGER NOT NULL CHECK(observed_length >= 0),
  message TEXT NOT NULL,
  remediation TEXT NOT NULL,
  UNIQUE(session_id, generation_id, source_table, source_column, source_ordinal)
) STRICT;

CREATE TABLE session_projection_aliases (
  session_id       TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id    TEXT NOT NULL,
  native_key       TEXT NOT NULL,
  source_entry_ref TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, native_key)
) STRICT;

CREATE TABLE session_projection_content (
  session_id       TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id    TEXT NOT NULL,
  source_entry_ref TEXT NOT NULL,
  relative_blob    TEXT NOT NULL,
  byte_length      INTEGER NOT NULL CHECK(byte_length >= 0),
  integrity_digest TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, source_entry_ref)
) STRICT;

CREATE TABLE session_projection_entries (
  session_id       TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id    TEXT NOT NULL,
  partition_id     INTEGER NOT NULL CHECK(partition_id >= 0),
  entry_index      INTEGER NOT NULL CHECK(entry_index >= 0),
  source_entry_ref TEXT,
  entry_json       TEXT NOT NULL,
  PRIMARY KEY (session_id, generation_id, partition_id, entry_index)
) STRICT;

CREATE TABLE session_projection_generations (
  session_id             TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id          TEXT NOT NULL,
  metadata_json          TEXT NOT NULL,
  title_refs_json        TEXT NOT NULL DEFAULT '[]',
  input_submission_count INTEGER CHECK(input_submission_count IS NULL OR (input_submission_count BETWEEN 0 AND 9007199254740991)),
  source_evidence_digest TEXT NOT NULL CHECK(length(source_evidence_digest) = 64),
  completeness           TEXT NOT NULL CHECK(completeness IN ('complete','incomplete_new')),
  index_format_version   INTEGER NOT NULL CHECK(index_format_version = 2),
  installed_at_ms        INTEGER NOT NULL CHECK(installed_at_ms >= 0),
  activated_at_ms        INTEGER CHECK(activated_at_ms IS NULL OR activated_at_ms >= 0),
  PRIMARY KEY (session_id, generation_id)
) STRICT;

CREATE TABLE "session_projection_sections" (
  session_id     TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id  TEXT NOT NULL,
  partition_id   INTEGER NOT NULL CHECK(partition_id >= 0),
  earlier_state  TEXT,
  PRIMARY KEY (session_id, generation_id, partition_id)
) STRICT;

CREATE TABLE session_publication_metadata (
 session_id TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
 capture_revision INTEGER NOT NULL CHECK (capture_revision > 0),
 schema_version INTEGER NOT NULL CHECK (schema_version > 0),
 metadata_json TEXT NOT NULL CHECK (json_valid(metadata_json)),
 metadata_hash TEXT NOT NULL CHECK (length(metadata_hash)=64 AND metadata_hash NOT GLOB '*[^0-9a-f]*'),
 content_hash TEXT NOT NULL CHECK (length(content_hash)=64 AND content_hash NOT GLOB '*[^0-9a-f]*'),
 captured_at INTEGER NOT NULL CHECK (captured_at > 0)
) STRICT;

CREATE TABLE session_publications (
  village_origin TEXT NOT NULL,
  owner_user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  remote_transcript_id TEXT NOT NULL,
  transcript_url TEXT NOT NULL,
  project_hash TEXT NOT NULL,
  operation_fingerprint TEXT NOT NULL CHECK(length(operation_fingerprint) = 64),
  content_hash TEXT NOT NULL CHECK(length(content_hash) = 64),
  visibility TEXT NOT NULL CHECK(visibility IN ('private', 'group', 'public')),
  published_at INTEGER NOT NULL CHECK(published_at > 0),
  remote_updated_at INTEGER NOT NULL CHECK(remote_updated_at >= published_at),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json)),
  PRIMARY KEY (village_origin, owner_user_id, project_hash, session_id),
  UNIQUE (village_origin, owner_user_id, remote_transcript_id),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE "session_relationship_evidence" (
  session_id      TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
  generation_id   TEXT NOT NULL,
  ordinal         INTEGER NOT NULL CHECK(ordinal >= 0),
  kind            TEXT NOT NULL,
  target_state    TEXT NOT NULL CHECK(target_state IN
    ('target_known','target_known_retained','explicit_none','unknown',
     'conflicting_current_native_evidence')),
  target_local_id TEXT,
  evidence        TEXT,
  anchor_kind TEXT,
  anchor_source_entry_ref TEXT,
  anchor_source_revision_ref TEXT,
  PRIMARY KEY (session_id, generation_id, kind)
) STRICT;

CREATE VIRTUAL TABLE session_search_fts USING fts5(
  content_preview, tool_input, tool_output, session_id UNINDEXED, entry_index UNINDEXED,
  content='session_search_source', content_rowid='rid', tokenize='unicode61 remove_diacritics 2');

CREATE TABLE session_search_state (
  id            INTEGER PRIMARY KEY CHECK(id = 1),
  needs_rebuild INTEGER NOT NULL CHECK(needs_rebuild IN (0,1))
) STRICT;

CREATE TABLE session_section_native_metadata (
  session_id TEXT NOT NULL,
  generation_id TEXT NOT NULL,
  partition_id INTEGER NOT NULL,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  native_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  source_entry_ref TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_message_role TEXT,
  attachment_turn_index INTEGER,
  attachment_tool_call_id TEXT,
  custom_type TEXT,
  data TEXT,
  PRIMARY KEY (session_id, generation_id, partition_id, ordinal),
  FOREIGN KEY (session_id, generation_id, partition_id)
    REFERENCES session_projection_sections(session_id, generation_id, partition_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE session_source_unavailability (
 session_id TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
 reason TEXT NOT NULL CHECK (reason IN ('original-source-unavailable-no-usable-saved-copy'))
) STRICT;

CREATE TABLE sessions (
    session_id TEXT PRIMARY KEY,
    parent_id TEXT REFERENCES sessions(session_id),
    model_harness TEXT NOT NULL CHECK (model_harness IN ('claude-code','opencode','codex','gemini-cli','cursor','antigravity','strike','pi')),
    model_id TEXT NOT NULL,
    opaque_host_id TEXT NOT NULL REFERENCES host_slugs(opaque_id),
    project_hash TEXT NOT NULL REFERENCES projects(project_hash),
    start_ms INTEGER NOT NULL,
    end_ms INTEGER NOT NULL,
    ingested_ms INTEGER NOT NULL,
    source_path TEXT NOT NULL,
    source_format TEXT NOT NULL CHECK (source_format IN ('jsonl','json')),
    schema_version INTEGER NOT NULL DEFAULT 1,
    git_branch TEXT,
    git_worktree TEXT,
    git_tracking TEXT,
    tool_version TEXT,
    pushed_at INTEGER,
    tags TEXT,
    index_version INTEGER NOT NULL DEFAULT 0,
    indexed_at INTEGER,
    license_id TEXT CHECK (license_id IN ('CC0-1.0', 'CC-BY-4.0', 'CC-BY-SA-4.0')),
    session_origin TEXT NOT NULL DEFAULT 'unknown' CHECK (session_origin IN ('user','agent','unknown')),
    origin_version INTEGER NOT NULL DEFAULT 0,
    session_entries_hash TEXT CHECK (session_entries_hash IS NULL OR (length(session_entries_hash) = 64 AND session_entries_hash NOT GLOB '*[^0-9a-f]*')),
    source_fingerprint BLOB,
    session_cwd TEXT,
    cwd_provenance_kind TEXT NOT NULL DEFAULT 'not_recovered' CHECK(cwd_provenance_kind IN ('source_exact','source_workspace','source_worktree','source_absent','not_recovered')),
    publication_capture_revision INTEGER NOT NULL DEFAULT 0 CHECK(publication_capture_revision >= 0),
    indexed_publication_capture_revision INTEGER NOT NULL DEFAULT 0 CHECK(indexed_publication_capture_revision >= 0)
, index_format_version INTEGER CHECK (index_format_version > 0), adapter_version INTEGER CHECK (adapter_version > 0), artifact_hash TEXT CHECK (artifact_hash IS NULL OR (length(artifact_hash) = 64 AND artifact_hash NOT GLOB '*[^0-9a-f]*')), metric_seed_json TEXT CHECK (metric_seed_json IS NULL OR json_valid(metric_seed_json)), indexed_input_hash TEXT CHECK (
    indexed_input_hash IS NULL OR (
        length(indexed_input_hash) = 64 AND indexed_input_hash NOT GLOB '*[^0-9a-f]*'
    )
), active_generation_id TEXT, root_session_id TEXT, session_purpose TEXT, input_submission_count INTEGER CHECK(input_submission_count IS NULL OR (input_submission_count BETWEEN 0 AND 9007199254740991)), content_sweep_pending INTEGER NOT NULL DEFAULT 0 CHECK(content_sweep_pending IN (0,1))) STRICT;

CREATE TABLE target_kinds (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE type_origins (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE value_domain_kinds (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
) STRICT;

CREATE INDEX idx_ann_annotator ON annotations(annotator_id);

CREATE INDEX idx_ann_content_hash ON annotations(content_hash) WHERE content_hash IS NOT NULL;

CREATE INDEX idx_ann_created_at ON annotations(created_at DESC);

CREATE INDEX idx_ann_target_annot ON annotation_target_annotations(target_annotation_id);

CREATE INDEX idx_ann_target_association
    ON annotation_target_associations(association_id);

CREATE INDEX idx_ann_target_entry ON annotation_target_entries(session_id, entry_index);

CREATE INDEX idx_ann_target_kind ON annotations(target_kind_id);

CREATE INDEX idx_ann_target_project ON annotation_target_projects(project_hash);

CREATE INDEX idx_ann_target_session ON annotation_target_sessions(session_id);

CREATE INDEX idx_ann_type_id ON annotations(annotation_type_id);

CREATE INDEX idx_annfam_class_id ON annotation_families(class_id);

CREATE INDEX idx_annotation_target_anchors_session_state
    ON annotation_target_anchors(session_id, state);

CREATE INDEX idx_annotator_kind ON annotators(kind_id);

CREATE INDEX idx_annotator_model ON annotators(model_id, provider_key) WHERE model_id IS NOT NULL;

CREATE INDEX idx_anntype_deps_reverse ON annotation_type_deps(depends_on_id);

CREATE INDEX idx_anntype_family_id ON annotation_types(family_id);

CREATE INDEX idx_anntype_status ON annotation_types(status_id);

CREATE INDEX idx_daily_project_hash ON daily_summary_by_project(project_hash);

CREATE INDEX idx_entries_ext_key ON session_entries_ext(key);

CREATE INDEX idx_generation_content_digest ON session_generation_content(session_id, digest);

CREATE INDEX idx_generation_entries_body ON session_generation_entries(session_id, body_digest);

CREATE INDEX idx_index_log_outcome ON index_log(outcome);

CREATE INDEX idx_index_log_session ON index_log(session_id);

CREATE INDEX idx_injection_log_project ON memory_injection_log(project_path, created_at);

CREATE INDEX idx_lesson_sources_lesson ON lesson_sources(lesson_id);

CREATE INDEX idx_lesson_sources_session ON lesson_sources(session_id);

CREATE INDEX idx_lessons_annotation ON lessons(episode_annotation_id);

CREATE UNIQUE INDEX idx_lessons_dedup ON lessons(topic, rule, failure_mode);

CREATE INDEX idx_lessons_session ON lessons(session_id);

CREATE INDEX idx_models_family ON models(family) WHERE family IS NOT NULL;

CREATE INDEX idx_publication_attempts_target ON publication_attempt_diagnostics(village_origin, owner_user_id, project_hash, session_id, attempted_at DESC);

CREATE INDEX idx_pulled_annotations_local_session ON pulled_annotations(local_session_id);

CREATE INDEX idx_pulled_annotations_transcript ON pulled_annotations(village_host, transcript_id);

CREATE INDEX idx_relationship_evidence_started_by_target
  ON session_relationship_evidence(kind, target_local_id, session_id, target_state);

CREATE INDEX idx_session_commands_name ON session_commands(command_name);

CREATE INDEX idx_session_commit_associations_session
    ON session_commit_associations(session_id, observed_commit_hash);

CREATE INDEX idx_session_commits_author ON session_commits(author_email) WHERE author_email IS NOT NULL;

CREATE INDEX idx_session_commits_time ON session_commits(commit_time) WHERE commit_time IS NOT NULL;

CREATE INDEX idx_session_content_captures_status ON session_content_captures(status);

CREATE INDEX idx_session_entries_depth ON session_entries(session_id, depth);

CREATE INDEX idx_session_entries_error ON session_entries(session_id, is_error) WHERE is_error = 1;

CREATE INDEX idx_session_entries_parent ON session_entries(session_id, parent_index) WHERE parent_index IS NOT NULL;

CREATE INDEX idx_session_entries_role ON session_entries(session_id, role);

CREATE INDEX idx_session_entries_type ON session_entries(session_id, entry_type);

CREATE INDEX idx_session_files_path ON session_files(file_path);

CREATE INDEX idx_session_publication_parent_uuid
  ON session_publication_metadata(json_extract(metadata_json, '$.parentUuid'))
  WHERE json_extract(metadata_json, '$.parentUuid') IS NOT NULL;

CREATE INDEX idx_session_publications_project ON session_publications(project_hash);

CREATE INDEX idx_sessions_harness ON sessions(model_harness);

CREATE INDEX idx_sessions_host ON sessions(opaque_host_id);

CREATE INDEX idx_sessions_parent ON sessions(parent_id) WHERE parent_id IS NOT NULL;

CREATE INDEX idx_sessions_project ON sessions(project_hash);

CREATE INDEX idx_sessions_start ON sessions(start_ms);

CREATE INDEX idx_sessions_sweep_pending ON sessions(session_id) WHERE content_sweep_pending = 1;

CREATE VIEW annotations_with_target AS
SELECT
    a.id, a.target_kind_id, tk.name AS target_kind,
    ts.session_id AS target_session_id,
    te.session_id AS target_entry_session_id,
    te.entry_index AS target_entry_index,
    te.end_index AS target_entry_end_index,
    ta.target_annotation_id,
    tp.project_hash AS target_project_hash,
    tsc.association_id AS target_association_id,
    a.annotator_id, ak.name AS annotator_kind,
    ann.name AS annotator_name, ann.display_name AS annotator_display_name,
    a.annotation_type_id, t.type_id, t.display_name AS type_name,
    f.family, c.class,
    a.value, a.confidence, a.reason, a.provenance,
    a.is_primary, a.content_hash, a.created_at, a.updated_at, a.superseded_by
FROM annotations a
    JOIN target_kinds tk ON a.target_kind_id = tk.id
    JOIN annotators ann ON a.annotator_id = ann.id
    JOIN annotator_kinds ak ON ann.kind_id = ak.id
    JOIN annotation_types t ON a.annotation_type_id = t.id
    JOIN annotation_families f ON t.family_id = f.id
    JOIN annotation_classes c ON f.class_id = c.id
    LEFT JOIN annotation_target_sessions ts ON a.id = ts.annotation_id
    LEFT JOIN annotation_target_entries te ON a.id = te.annotation_id
    LEFT JOIN annotation_target_annotations ta ON a.id = ta.annotation_id
    LEFT JOIN annotation_target_projects tp ON a.id = tp.annotation_id
    LEFT JOIN annotation_target_associations tsc ON a.id = tsc.annotation_id;

CREATE VIEW session_search_source(rid, session_id, entry_index, content_preview, tool_input, tool_output) AS
  SELECT rowid, session_id, entry_index, content_preview, tool_input, tool_output
    FROM session_entries
  UNION ALL
  SELECT body_id, session_id, entry_index, content_preview, tool_input, tool_output
    FROM session_entry_bodies;

CREATE TRIGGER session_entries_ad AFTER DELETE ON session_entries BEGIN
    INSERT INTO session_entries_fts(session_entries_fts, rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    VALUES ('delete', old.rowid, old.content_preview, old.tool_input, old.tool_output, old.session_id, old.entry_index);
END;

CREATE TRIGGER session_entries_ai AFTER INSERT ON session_entries BEGIN
    INSERT INTO session_entries_fts(rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    VALUES (new.rowid, new.content_preview, new.tool_input, new.tool_output, new.session_id, new.entry_index);
END;

CREATE TRIGGER session_entries_au AFTER UPDATE ON session_entries BEGIN
    INSERT INTO session_entries_fts(session_entries_fts, rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    VALUES ('delete', old.rowid, old.content_preview, old.tool_input, old.tool_output, old.session_id, old.entry_index);
    INSERT INTO session_entries_fts(rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    VALUES (new.rowid, new.content_preview, new.tool_input, new.tool_output, new.session_id, new.entry_index);
END;

CREATE TRIGGER session_entry_bodies_fts_ai AFTER INSERT ON session_entry_bodies BEGIN
  INSERT INTO session_search_fts(rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    SELECT rid, content_preview, tool_input, tool_output, session_id, entry_index
      FROM session_search_source WHERE rid = new.body_id;
END;

CREATE TRIGGER session_entry_bodies_fts_bd BEFORE DELETE ON session_entry_bodies BEGIN
  INSERT INTO session_search_fts(session_search_fts, rowid, content_preview, tool_input, tool_output, session_id, entry_index)
    SELECT 'delete', rid, content_preview, tool_input, tool_output, session_id, entry_index
      FROM session_search_source WHERE rid = old.body_id;
END;

CREATE TRIGGER session_entry_bodies_immutable BEFORE UPDATE ON session_entry_bodies
BEGIN
  SELECT RAISE(ABORT, 'session_entry_bodies rows are immutable; insert a new entry instead');
END;

CREATE TRIGGER session_generations_immutable BEFORE UPDATE ON session_generations
BEGIN
  SELECT RAISE(ABORT, 'generation rows are immutable; a new generation gets a new row');
END;

CREATE TRIGGER sessions_publication_metadata_changed
AFTER UPDATE OF parent_id,model_harness,model_id,opaque_host_id,project_hash,
 start_ms,end_ms,ingested_ms,source_path,source_format,schema_version,
 git_branch,git_worktree,git_tracking,tool_version,session_origin ON sessions
BEGIN
 UPDATE sessions SET indexed_publication_capture_revision=0, cwd_provenance_kind='not_recovered' WHERE session_id=NEW.session_id;
END;

INSERT INTO "annotation_classes" ("id", "class", "display_name", "description") VALUES ('21d2f994-8f86-5a0b-bd47-063f96f3f345', 'quality', 'Quality', 'Assessments of session or turn quality and outcomes');
INSERT INTO "annotation_classes" ("id", "class", "display_name", "description") VALUES ('896befc6-f370-5094-9b54-4f71254274fb', 'metadata', 'Metadata', 'Descriptive classifications of session properties');
INSERT INTO "annotation_classes" ("id", "class", "display_name", "description") VALUES ('39c9b0d9-9196-578e-a8fb-982481c4c38c', 'behavior', 'Behavior', 'Session behavior pattern classifications (post-MVP)');
INSERT INTO "annotation_classes" ("id", "class", "display_name", "description") VALUES ('2c001cd0-2d06-50b5-b441-2929eaecc8e2', 'research', 'Research', 'Research-specific annotation types for transcript analysis studies');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('d4cc6f70-f531-5020-aed7-998217b01b66', 'session_quality', '21d2f994-8f86-5a0b-bd47-063f96f3f345', 'Session Quality', 'Session-level quality assessments');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('e29404c6-3581-5389-bd72-c51daab898e4', 'turn_quality', '21d2f994-8f86-5a0b-bd47-063f96f3f345', 'Turn Quality', 'Turn-level quality assessments');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('57daf000-489b-5972-ad63-6257158688f4', 'session_metadata', '896befc6-f370-5094-9b54-4f71254274fb', 'Session Metadata', 'Session-level descriptive properties');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('b3c78b65-5b61-5123-94da-8b589d74a7d3', 'turn_metadata', '896befc6-f370-5094-9b54-4f71254274fb', 'Turn Metadata', 'Turn-level descriptive properties');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('f8076c34-e8b7-51ee-8571-cf8c63ba530e', 'session_behavior', '39c9b0d9-9196-578e-a8fb-982481c4c38c', 'Session Behavior', 'Session-level behavior patterns');
INSERT INTO "annotation_families" ("id", "family", "class_id", "display_name", "description") VALUES ('89a4a5fd-871b-555a-8ca5-b489ccab835f', 'episode_friction', '2c001cd0-2d06-50b5-b441-2929eaecc8e2', 'Episode Friction', 'Classification of friction episodes in developer-agent interaction transcripts');
INSERT INTO "annotation_statuses" ("id", "name") VALUES (1, 'proposed');
INSERT INTO "annotation_statuses" ("id", "name") VALUES (2, 'active');
INSERT INTO "annotation_statuses" ("id", "name") VALUES (3, 'deprecated');
INSERT INTO "annotation_statuses" ("id", "name") VALUES (4, 'retired');
INSERT INTO "annotation_type_deps" ("annotation_type_id", "depends_on_id", "required", "rationale") VALUES ('7bb9be1a-e95c-591a-88f0-9686e2c018e2', 'c6d095e6-b1ad-5270-bee5-116b32fc54a3', 0, 'Scope classification provides context for outcome assessment but is not required');
INSERT INTO "annotation_type_deps" ("annotation_type_id", "depends_on_id", "required", "rationale") VALUES ('7bb9be1a-e95c-591a-88f0-9686e2c018e2', 'a2c446b9-9c48-5e87-bf2e-2d5606b47c30', 1, 'Entry-level resolution evidence annotations support the session-level outcome classification');
INSERT INTO "annotation_type_deps" ("annotation_type_id", "depends_on_id", "required", "rationale") VALUES ('e4be9441-b3a3-5c98-ae69-5b5826b5bcb5', 'afd2a094-86af-5e9a-b38c-e70bf1a23846', 1, 'Entry-level frustration signal annotations support the session-level frustration classification');
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('5167c9e2-e47f-5b8a-9298-893e856aba3f', 1);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('7bb9be1a-e95c-591a-88f0-9686e2c018e2', 1);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('e4be9441-b3a3-5c98-ae69-5b5826b5bcb5', 1);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('c6d095e6-b1ad-5270-bee5-116b32fc54a3', 1);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('7bb9be1a-e95c-591a-88f0-9686e2c018e2', 4);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('c6d095e6-b1ad-5270-bee5-116b32fc54a3', 4);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('afd2a094-86af-5e9a-b38c-e70bf1a23846', 2);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('a2c446b9-9c48-5e87-bf2e-2d5606b47c30', 2);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('c1239eed-8182-5d15-b288-80bd48d235e4', 3);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('c2cf426f-2312-51d2-9398-43d834600f38', 2);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('91f30549-eaf7-59b9-90ad-1b6d5d45bcc3', 2);
INSERT INTO "annotation_type_target_kinds" ("annotation_type_id", "target_kind_id") VALUES ('1782e663-f3e0-548e-949c-e3120213fddb', 2);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('5167c9e2-e47f-5b8a-9298-893e856aba3f', 'quality.session_approval', 1, 'Session Approval', 'Binary approval or denial of overall session quality. Used for RLHF-style preference signals on AI agent sessions.', 'd4cc6f70-f531-5020-aed7-998217b01b66', 1, 'text', '["approve","deny"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('7bb9be1a-e95c-591a-88f0-9686e2c018e2', 'quality.session_outcome', 1, 'Session Outcome', 'Categorical classification of how the session concluded. Resolved = task completed; partial = progress but unfinished; failed = approach did not work; abandoned = user stopped.', 'd4cc6f70-f531-5020-aed7-998217b01b66', 1, 'text', '["resolved","partial","failed","abandoned"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 2);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('e4be9441-b3a3-5c98-ae69-5b5826b5bcb5', 'quality.user_frustration', 1, 'User Frustration', 'Detection of user frustration signals in session interaction patterns. Detected = frustration indicators present; not_detected = normal interaction.', 'd4cc6f70-f531-5020-aed7-998217b01b66', 1, 'text', '["detected","not_detected"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('c6d095e6-b1ad-5270-bee5-116b32fc54a3', 'metadata.session_scope', 1, 'Session Scope', 'Classification of the type of work performed in the session.', '57daf000-489b-5972-ad63-6257158688f4', 1, 'text', '["feature","bug","refactor","docs","config","unknown"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('afd2a094-86af-5e9a-b38c-e70bf1a23846', 'quality.frustration_signal', 1, 'Frustration Signal', 'Entry-level detection of user frustration signals (expletive patterns). Marks individual turns where frustration was detected.', 'e29404c6-3581-5389-bd72-c51daab898e4', 1, 'text', '["detected","not_detected"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('a2c446b9-9c48-5e87-bf2e-2d5606b47c30', 'quality.resolution_evidence', 1, 'Resolution Evidence', 'Entry-level detection of resolution evidence phrases in assistant responses. Marks individual turns where resolution evidence was found.', 'e29404c6-3581-5389-bd72-c51daab898e4', 1, 'text', '["present","absent"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('c1239eed-8182-5d15-b288-80bd48d235e4', 'quality.annotation_approval', 1, 'Annotation Approval', 'Human approval or rejection of an auto-detected annotation. A meta-annotation: annotates another annotation.', 'd4cc6f70-f531-5020-aed7-998217b01b66', 1, 'text', '["approved","rejected","perceived"]', NULL, 3, 1, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('1a174d56-5057-576f-b8a6-91656939a0e5', 'research.friction_episode', 2, 'Friction Episode', 'Classification of friction episodes in developer-agent transcripts. Categories: BAD_HANDOFF (communication/takeover gaps), BAD_OUTPUT (broken/wrong artifacts), BAD_PROCESS (wrong method/workflow).', '89a4a5fd-871b-555a-8ca5-b489ccab835f', 1, 'text', '["bad_handoff","bad_output","bad_process"]', NULL, 2, 2, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('c2cf426f-2312-51d2-9398-43d834600f38', 'user.custom_label', 1, 'Custom label', 'A user-authored free-text label on a single turn. Any short note the user types to mark a moment in the transcript.', 'b3c78b65-5b61-5123-94da-8b589d74a7d3', 2, 'text', '', NULL, 2, 2, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('1782e663-f3e0-548e-949c-e3120213fddb', 'quality.turn_outcome', 1, 'Turn outcome', 'A human verdict on a single turn: good, neutral, or bad. Set from the transcript viewer''s per-turn labeling modal.', 'e29404c6-3581-5389-bd72-c51daab898e4', 1, 'text', '["good","neutral","bad"]', NULL, 2, 2, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 2);
INSERT INTO "annotation_types" ("id", "type_id", "version", "display_name", "description", "family_id", "value_domain_kind_id", "datatype", "value_constraint", "lower_is_better", "status_id", "origin_id", "priority_override", "created_at", "updated_at", "deprecated_at", "superseded_by", "scale_kind_id") VALUES ('91f30549-eaf7-59b9-90ad-1b6d5d45bcc3', 'quality.turn_flag', 1, 'Turn flag', 'An optional friction tag on a single turn: none, error, retry_loop, revert, or highlight. Set from the transcript viewer''s per-turn labeling modal.', 'e29404c6-3581-5389-bd72-c51daab898e4', 1, 'text', '["none","error","retry_loop","revert","highlight"]', NULL, 2, 2, NULL, CAST(strftime('%s','now') AS INTEGER) * 1000, NULL, NULL, NULL, 1);
INSERT INTO "annotator_kinds" ("id", "name") VALUES (1, 'human');
INSERT INTO "annotator_kinds" ("id", "name") VALUES (2, 'agent');
INSERT INTO "annotator_kinds" ("id", "name") VALUES (3, 'rule');
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('76a5e5f6-9598-533b-8635-5e7c73c917dc', 3, 'outcome-classifier', 'Outcome Classifier', 'Rule-based classifier that determines session outcome from metrics and turn patterns.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('8f8cc852-92b6-5aa4-b4f6-4f55e9d1f196', 3, 'frustration-classifier', 'Frustration Classifier', 'Rule-based classifier that detects user frustration signals from interaction patterns.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('bf71bffb-3af9-53c2-ac1c-de1f4d870a40', 3, 'scope-classifier', 'Scope Classifier', 'Rule-based classifier that determines session scope from tool usage and content patterns.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('835e67a0-c0f3-5023-88cd-2d59cd15313e', 1, 'human-web', 'Web Dashboard User', 'Human annotations created through the Peasant web dashboard.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('2537b2d1-6a47-57a1-a7e1-72568bfe3975', 3, 'frustration-signal-classifier', 'Frustration Signal Classifier', 'Rule-based classifier that detects frustration signals at individual entry level.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "annotators" ("id", "kind_id", "name", "display_name", "description", "model_id", "provider_key", "status", "created_at") VALUES ('32238cf8-cd88-5927-adbb-d94843a1872b', 3, 'resolution-evidence-classifier', 'Resolution Evidence Classifier', 'Rule-based classifier that detects resolution evidence at individual entry level.', NULL, NULL, 'active', CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO "scale_kinds" ("id", "name") VALUES (1, 'nominal');
INSERT INTO "scale_kinds" ("id", "name") VALUES (2, 'ordinal');
INSERT INTO "scale_kinds" ("id", "name") VALUES (3, 'continuous');
INSERT INTO "session_search_state" ("id", "needs_rebuild") VALUES (1, 0);
INSERT INTO "target_kinds" ("id", "name") VALUES (1, 'session');
INSERT INTO "target_kinds" ("id", "name") VALUES (2, 'entry');
INSERT INTO "target_kinds" ("id", "name") VALUES (3, 'annotation');
INSERT INTO "target_kinds" ("id", "name") VALUES (4, 'project');
INSERT INTO "target_kinds" ("id", "name") VALUES (5, 'association');
INSERT INTO "type_origins" ("id", "name") VALUES (1, 'system');
INSERT INTO "type_origins" ("id", "name") VALUES (2, 'user');
INSERT INTO "type_origins" ("id", "name") VALUES (3, 'group');
INSERT INTO "value_domain_kinds" ("id", "name") VALUES (1, 'enumerated');
INSERT INTO "value_domain_kinds" ("id", "name") VALUES (2, 'described');
DELETE FROM "session_entries_fts_config";
INSERT INTO "session_entries_fts_config" ("k", "v") VALUES ('version', 4);

DELETE FROM "session_entries_fts_data";
INSERT INTO "session_entries_fts_data" ("id", "block") VALUES (1, X'000000000000');
INSERT INTO "session_entries_fts_data" ("id", "block") VALUES (10, X'00000000000000');

DELETE FROM "session_search_fts_config";
INSERT INTO "session_search_fts_config" ("k", "v") VALUES ('version', 4);

DELETE FROM "session_search_fts_data";
INSERT INTO "session_search_fts_data" ("id", "block") VALUES (1, X'');
INSERT INTO "session_search_fts_data" ("id", "block") VALUES (10, X'00000000000000');

PRAGMA user_version = 63;
