package redactionpolicygen_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/peasant-labs/peasant/internal/config"
	"github.com/peasant-labs/peasant/internal/redactionpolicygen"
	"github.com/peasant-labs/peasant/internal/testutil"
	"github.com/peasant-labs/redact"
)

// TestRedactionPolicyFreshness_MatchesGenerator is the gate that makes the
// wizard's copy of the policy a MIRROR rather than a second opinion.
//
// ITS ACCEPTANCE TEST, stated as the production change that must turn it red:
// giving another level the offered disposition in internal/config's table - which
// is the realistic future the table exists to absorb. Before this file existed
// that change turned internal/config, internal/api and cmd/peasant red and left
// all seven web test files green, with the wizard still offering only the old
// menu and one of its tests asserting that the newly-offered level stay hidden.
// The web suite cemented the stale state instead of catching it.
//
// It fires in both directions, which a hand-written mirror could not: narrowing
// the Go set without regenerating fails here too.
func TestRedactionPolicyFreshness_MatchesGenerator(t *testing.T) {
	t.Parallel()
	want, err := redactionpolicygen.GenerateRedactionPolicyTS()
	if err != nil {
		t.Fatalf("generate the wizard redaction policy: %v", err)
	}

	path := filepath.Join(testutil.ModuleRoot(t), redactionpolicygen.RedactionPolicyRelPath.String())
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the committed wizard policy at %s: %v\nRegenerate with `go run ./cmd/gen-redaction-policy`.", path, err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf(
			"STALE committed wizard policy: %s no longer matches internal/config.\n"+
				"  what: the share wizard's level set, default, and refusal reasons are not what the generator emits.\n"+
				"  why:  the disposition table changed without a regeneration, or the file was hand-edited.\n"+
				"  means: the wizard is presenting a menu the product no longer agrees with - offering a level it would "+
				"refuse, or hiding one it has started to offer, with a locally-rendered explanation to match.\n"+
				"  fix:  run `go run ./cmd/gen-redaction-policy` and commit the result.",
			path)
	}
}

// TestRedactionPolicyGenerator_CarriesEveryLevelAndAReasonForEachRefusal checks
// the SHAPE of what is generated, so the freshness gate above is comparing two
// renderings of the whole policy rather than two renderings of part of it.
//
// A generator that silently emitted an empty reason map would keep the gate green
// for as long as nobody regenerated by hand, and the wizard would fall back to
// explaining nothing.
func TestRedactionPolicyGenerator_CarriesEveryLevelAndAReasonForEachRefusal(t *testing.T) {
	t.Parallel()
	data, err := redactionpolicygen.GenerateRedactionPolicyTS()
	if err != nil {
		t.Fatalf("generate the wizard redaction policy: %v", err)
	}
	generated := string(data)

	for _, level := range redact.AllRedactionLevels() {
		if !strings.Contains(generated, "'"+level.String()+"'") {
			t.Errorf("the generated policy never names the %q level, so the wizard's level union is narrower than the "+
				"engine's and a rule fixture carrying that level would not type-check", level)
		}
		if config.RedactionLevelOffered(level) {
			continue
		}
		// The reason is the sentence the user reads when the wizard refuses. An
		// unselectable level with no entry leaves the step refusing without saying
		// why, which is the one thing a refusal has to do.
		//
		// The head is taken before the surface-specific tail, which is the part
		// that legitimately differs between the CLI, the local API and the wizard.
		// A missing separator FAILS rather than skipping the check: a reason whose
		// shape changed would otherwise take this assertion silently with it, which
		// is the same "green because nothing was measured" the corpora elsewhere
		// exist to prevent.
		reason := config.RedactionRefusalReason(level, "")
		head, _, found := strings.Cut(reason, ", so ")
		if !found {
			t.Fatalf("the refusal reason for %q no longer separates its shared head from its per-surface tail with %q, so "+
				"this test can no longer tell whether the generated file carries the reason at all; reason: %s",
				level, ", so ", reason)
		}
		if !strings.Contains(generated, head) {
			t.Errorf("the generated policy carries no refusal reason for the unselectable level %q; the wizard would "+
				"refuse it with no explanation", level)
		}
	}
	if !strings.Contains(generated, "'"+config.RecommendedRedactionLevel.String()+"';") {
		t.Errorf("the generated policy does not set the wizard's starting level to the recommended %q",
			config.RecommendedRedactionLevel)
	}
}
