// Package redactionpolicygen generates the web share wizard's view of the
// redaction policy (web/src/lib/share/redaction-policy.generated.ts) FROM
// internal/config.
//
// The wizard needs three facts that only Go knows: every level the engine
// defines, the subset a user may CHOOSE, and why each of the others cannot be
// chosen. All three were hand-written on the TypeScript side, with a comment
// saying they mirrored the Go values. A comment is not a gate: widening the
// offered set turned internal/config, internal/api and cmd/peasant red and left
// the whole web suite green, with the wizard still presenting the old menu and a
// test actively asserting that the newly-offered level stay hidden. The mirror
// cemented the stale state rather than catching it.
//
// A second hand-written copy that currently agrees is the same defect with a
// fresh timestamp, so this generates the file instead, following the pattern
// internal/redactmock already uses for the session-detail mock: a freshness test
// asserts the committed TypeScript is byte-identical to this output, so the
// wizard cannot drift from the policy in either direction. Regenerate with
// `go run ./cmd/gen-redaction-policy`.
package redactionpolicygen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/peasant-labs/peasant/internal/config"
	"github.com/peasant-labs/redact"
)

// GeneratedPath is the repository-relative location of a generated artifact.
type GeneratedPath string

func (p GeneratedPath) String() string { return string(p) }

// RedactionPolicyRelPath is the committed artifact, relative to the module root.
const RedactionPolicyRelPath GeneratedPath = "web/src/lib/share/redaction-policy.generated.ts"

// wizardConsequence is the caller-specific tail of every refusal reason rendered
// here.
//
// config.RedactionRefusalReason ends "..., so <consequence>", and what follows
// differs by surface: a CLI run stops, a publish would not apply what was named.
// In the wizard the level chooses what the review below it describes, so the
// consequence is that a scan at that level would describe no run this version can
// perform. It is stated once, here, rather than per level.
const wizardConsequence = "a scan at that level would not describe any run this version can perform"

const tsHeader = `// Code generated by cmd/gen-redaction-policy. DO NOT EDIT.
//
// The redaction policy, as the share wizard needs it. Generated from
// internal/config so the wizard cannot present a level the product refuses, and
// cannot go on hiding one it has started to offer.
//
// These values were hand-written here once, under a comment saying they mirrored
// the Go side. Widening the offered set then turned three Go packages red and
// left every web test green - including one that asserted the newly-offered level
// must stay hidden. Regenerate with ` + "`go run ./cmd/gen-redaction-policy`" + `; a
// freshness test fails if this file and internal/config disagree.

`

// GenerateRedactionPolicyTS renders the committed TypeScript module.
func GenerateRedactionPolicyTS() ([]byte, error) {
	levels := redact.AllRedactionLevels()
	if len(levels) == 0 {
		return nil, fmt.Errorf(
			"gen-redaction-policy: the engine defines no redaction levels, so the generated wizard contract would carry an "+
				"empty level union.\nWhat went wrong: redact.AllRedactionLevels is empty.\nWhere: %s, generating %s.\n"+
				"When: at codegen, before anything was written.\nMeans: the wizard would type-check against a union no value "+
				"can satisfy, and every level would render as unselectable.\nFix: restore the level enumeration in "+
				"github.com/peasant-labs/redact.", "redactionpolicygen.GenerateRedactionPolicyTS", RedactionPolicyRelPath)
	}
	if len(config.OfferedRedactionLevels) == 0 {
		return nil, fmt.Errorf(
			"gen-redaction-policy: no redaction level is offered, so the wizard would have nothing to select.\n"+
				"What went wrong: config.OfferedRedactionLevels is empty.\nWhere: %s, generating %s.\n"+
				"When: at codegen, before anything was written.\nMeans: the share flow could not be completed at all - "+
				"every level would be refused and the default would not be selectable.\nFix: give at least one level the "+
				"offered disposition in internal/config's disposition table.",
			"redactionpolicygen.GenerateRedactionPolicyTS", RedactionPolicyRelPath)
	}

	var buf bytes.Buffer
	buf.WriteString(tsHeader)

	buf.WriteString("/**\n")
	buf.WriteString(" * Every redaction level the engine defines.\n")
	buf.WriteString(" *\n")
	buf.WriteString(" * This is the RULE-ACTIVATION axis, not a menu: each rule declares the level at\n")
	buf.WriteString(" * which it starts firing.\n")
	buf.WriteString(" * What a user may CHOOSE is the narrower set below.\n")
	buf.WriteString(" */\n")
	buf.WriteString("export const ALL_REDACTION_LEVELS = [")
	writeLevelList(&buf, levels)
	buf.WriteString("] as const;\n\n")
	buf.WriteString("/** A level the engine can apply. */\n")
	buf.WriteString("export type RedactionLevel = (typeof ALL_REDACTION_LEVELS)[number];\n\n")

	buf.WriteString("/**\n")
	buf.WriteString(" * The levels this version offers a user, from config.OfferedRedactionLevels.\n")
	buf.WriteString(" *\n")
	buf.WriteString(" * Asking for any other level produces an opaque 400 mid-wizard, so the step\n")
	buf.WriteString(" * refuses locally with the matching explanation instead.\n")
	buf.WriteString(" */\n")
	buf.WriteString("export const SELECTABLE_REDACTION_LEVELS = [")
	writeLevelList(&buf, config.OfferedRedactionLevels)
	buf.WriteString("] as const;\n\n")
	buf.WriteString("/** A level a user may choose. */\n")
	buf.WriteString("export type SelectableRedactionLevel = (typeof SELECTABLE_REDACTION_LEVELS)[number];\n\n")

	buf.WriteString("/** The level the wizard starts on, from config.RecommendedRedactionLevel. */\n")
	buf.WriteString(fmt.Sprintf("export const DEFAULT_REDACTION_LEVEL: SelectableRedactionLevel = %s;\n\n",
		tsString(config.RecommendedRedactionLevel.String())))

	buf.WriteString("/**\n")
	buf.WriteString(" * Why each unselectable level cannot be chosen, from\n")
	buf.WriteString(" * config.RedactionRefusalReason - the same sentence the CLI and the local API\n")
	buf.WriteString(" * give for the same level, rather than a third phrasing of it.\n")
	buf.WriteString(" */\n")
	buf.WriteString("export const UNSELECTABLE_REDACTION_LEVEL_REASONS: Readonly<Record<string, string>> = {\n")
	for _, level := range levels {
		if config.RedactionLevelOffered(level) {
			continue
		}
		buf.WriteString(fmt.Sprintf("  %s: %s,\n",
			tsString(level.String()), tsString(config.RedactionRefusalReason(level, wizardConsequence))))
	}
	buf.WriteString("};\n\n")

	buf.WriteString("/**\n")
	buf.WriteString(" * What redaction actually does, in one sentence, from\n")
	buf.WriteString(" * config.RedactionScopeSentence.\n")
	buf.WriteString(" *\n")
	buf.WriteString(" * It is deliberately hedged: pattern matching finds KNOWN patterns and cannot\n")
	buf.WriteString(" * promise it found every one. A completeness claim here would be a defect, so\n")
	buf.WriteString(" * the sentence is generated rather than re-typed - the wizard's hand-written\n")
	buf.WriteString(" * copy had already drifted from the Go one (\"shared\" against \"published\" as\n")
	buf.WriteString(" * recorded) while config claimed the hedge lived in exactly one place.\n")
	buf.WriteString(" */\n")
	buf.WriteString(fmt.Sprintf("export const REDACTION_SCOPE_SENTENCE = %s;\n", tsString(config.RedactionScopeSentence())))
	return buf.Bytes(), nil
}

func writeLevelList(buf *bytes.Buffer, levels []redact.RedactionLevel) {
	for index, level := range levels {
		if index > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(tsString(level.String()))
	}
}

// tsString renders a Go string as a single-quoted TS literal, matching the
// surrounding code style. Escaping goes through encoding/json - with HTML
// escaping disabled so a reason sentence keeps its punctuation literal - and the
// surrounding quotes are then swapped.
func tsString(value string) string {
	var buf bytes.Buffer
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	_ = encoder.Encode(value)
	quoted := string(bytes.TrimRight(buf.Bytes(), "\n"))
	// A double-quoted JSON body needs its escaped double quotes relaxed and its
	// single quotes escaped for the single-quoted TS form.
	inner := strings.ReplaceAll(strings.ReplaceAll(quoted[1:len(quoted)-1], `\"`, `"`), `'`, `\'`)
	return "'" + inner + "'"
}
