#!/usr/bin/env bash
# Generate THIRD_PARTY_NOTICES: the license texts of every third-party Go module
# compiled into the peasant binary.
#
# WHY: `go build` produces a static binary that keeps none of its dependencies'
# license files. peasant ships that binary through Homebrew, deb, and rpm. The
# permissive licenses of those dependencies (MIT / BSD / ISC / Apache-2.0) all
# require their copyright and permission notices to travel with a binary
# redistribution. This script reproduces those notices in one file.
#
# HOW: it enumerates the modules actually linked into ./cmd/peasant across every
# release target (linux/darwin x amd64/arm64), finds each module's license file
# in the Go module cache, and concatenates them in a stable order. The module
# set is pinned by go.sum and the license text is content-addressed in the cache,
# so the output is byte-stable. A CI job regenerates this file and fails on any
# diff (see .github/workflows/tests.yml), so it can never drift from the deps.
#
# This reads license text straight from the cache instead of classifying license
# NAMES, because the legal obligation is on the text. A name-classifier silently
# drops modules it cannot recognize (e.g. the modernc.org SQLite stack), which is
# the one failure this file must not have. The separate copyleft guard
# (go-licenses check, in CI) owns license CLASSIFICATION.
#
# Scope: Go modules only. The embedded web dashboard (web/out) bundles npm
# packages whose notices are tracked as a separate follow-on.
#
# Usage: scripts/gen-third-party-notices.sh   (or: make third-party-notices)
set -euo pipefail
export LC_ALL=C

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_file="${repo_root}/THIRD_PARTY_NOTICES"
pkg="./cmd/peasant"

# The main module itself is not a third-party notice; its grant is the top-level
# LICENSE. Skip it by module path.
main_module="$(cd "${repo_root}" && go list -m 2>/dev/null | head -n1)"

# Union of linked modules across every shipped platform. A single GOOS/GOARCH
# misses platform-specific dependencies (e.g. darwin-only modules).
mods_tmp="$(mktemp)"
trap 'rm -f "${mods_tmp}"' EXIT
for pair in linux/amd64 linux/arm64 darwin/amd64 darwin/arm64; do
  GOOS="${pair%/*}" GOARCH="${pair#*/}" go list -deps \
    -f '{{if not .Standard}}{{if .Module}}{{.Module.Path}}@{{.Module.Version}}{{end}}{{end}}' \
    "${pkg}"
done | sort -u | grep . > "${mods_tmp}"

# Build the file in a temp buffer, then move it into place atomically.
buf_tmp="$(mktemp)"
trap 'rm -f "${mods_tmp}" "${buf_tmp}"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY SOFTWARE NOTICES
============================

The peasant binary is a static build. It includes the third-party Go modules
listed below, and this file reproduces their license texts as their permissive
licenses require for binary redistribution.

Do not edit this file by hand. It is generated from the module set pinned in
go.sum. To regenerate it, run: make third-party-notices

This file covers Go modules only. The embedded web dashboard bundles npm
packages whose notices are tracked separately.

HEADER

  while IFS= read -r mod; do
    path="${mod%@*}"
    [ "${path}" = "${main_module}" ] && continue

    dir="$(go list -m -f '{{.Dir}}' "${mod}" 2>/dev/null || true)"
    if [ -z "${dir}" ] || [ ! -d "${dir}" ]; then
      echo "gen-third-party-notices: no module cache dir for ${mod}" >&2
      exit 1
    fi

    # All license-like files at the module root, in a stable order. Apache
    # modules ship both LICENSE and NOTICE; both must be reproduced.
    # -iname 'LICENSE*' also matches source files such as license.go, so exclude
    # common source extensions defensively.
    mapfile -t lic_files < <(
      find "${dir}" -maxdepth 1 -type f \
        \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) \
        ! -iname '*.go' ! -iname '*.json' \
        -printf '%f\n' 2>/dev/null | sort
    )
    if [ "${#lic_files[@]}" -eq 0 ]; then
      echo "gen-third-party-notices: no license file found for ${mod} (${dir})" >&2
      exit 1
    fi

    for name in "${lic_files[@]}"; do
      printf '%s\n' "================================================================================"
      printf 'Module: %s\n' "${mod}"
      printf 'File:   %s\n' "${name}"
      printf '%s\n\n' "================================================================================"
      cat "${dir}/${name}"
      printf '\n'
    done
  done < "${mods_tmp}"
} > "${buf_tmp}"

mv "${buf_tmp}" "${out_file}"
trap 'rm -f "${mods_tmp}"' EXIT

count="$(grep -c '^Module: ' "${out_file}" || true)"
echo "wrote ${out_file} (${count} license entries)"
